In [1]:
import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
import os
import seaborn as sns
from datetime import datetime
import fnmatch
import sys
import glob

Bad key text.latex.unicode in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 112 ('text.latex.unicode : False # use "ucs" and "inputenc" LaTeX packages for handling')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key savefig.frameon in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 423 ('savefig.frameon : True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key nbagg.transparent in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 426 ('nbagg.transparent: True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key pgf.debug in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 446 ('pgf.debug           : False')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.level in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 477 ('verbose.level  : silent      # one of silent, helpful, debug, debug-annoying')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.fileo in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 478 ('verbose.fileo  : sys.stdout  # a log filename, sys.stdout or sys.stderr')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key animation.mencoder_path in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 509 ('animation.mencoder_path: mencoder')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key animation.mencoder_args in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 512 ('animation.mencoder_args:          # Additional arguments to pass to mencoder')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

In [2]:
xl_list = glob.glob('./Stats\**\*.xlsx', 
                   recursive = True)

for file in xl_list:
    print (file)

./Stats\2007-08\2007-08goalies.xlsx
./Stats\2007-08\2007-08skaters.xlsx
./Stats\2007-08\2007-08skaters_adv.xlsx
./Stats\2008-09\2008-09goalies.xlsx
./Stats\2008-09\2008-09goalies_shootout.xlsx
./Stats\2008-09\2008-09skaters.xlsx
./Stats\2008-09\2008-09skaters_adv.xlsx
./Stats\2008-09\2008-09skaters_shootout.xlsx
./Stats\2009-10\2009-10goalies.xlsx
./Stats\2009-10\2009-10goalies_shootout.xlsx
./Stats\2009-10\2009-10skaters.xlsx
./Stats\2009-10\2009-10skaters_adv.xlsx
./Stats\2009-10\2009-10skaters_shootout.xlsx
./Stats\2010-11\2010-11goalies.xlsx
./Stats\2010-11\2010-11goalies_shootout.xlsx
./Stats\2010-11\2010-11skaters.xlsx
./Stats\2010-11\2010-11skaters_adv.xlsx
./Stats\2010-11\2010-11skaters_shootout.xlsx
./Stats\2011-12\2011-12goalies.xlsx
./Stats\2011-12\2011-12goalies_shootout.xlsx
./Stats\2011-12\2011-12skaters.xlsx
./Stats\2011-12\2011-12skaters_adv.xlsx
./Stats\2011-12\2011-12skaters_shootout.xlsx
./Stats\2012-13\2012-13goalies.xlsx
./Stats\2012-13\2012-13goalies_shootout.xlsx
./Stats\2012-13\2012-13skaters.xlsx
./Stats\2012-13\2012-13skaters_adv.xlsx
./Stats\2012-13\2012-13skaters_shootout.xlsx
./Stats\2013-14\2013-14goalies.xlsx
./Stats\2013-14\2013-14goalies_shootout.xlsx
./Stats\2013-14\2013-14skaters.xlsx
./Stats\2013-14\2013-14skaters_adv.xlsx
./Stats\2013-14\2013-14skaters_shootout.xlsx
./Stats\2014-15\2014-15goalies.xlsx
./Stats\2014-15\2014-15goalies_shootout.xlsx
./Stats\2014-15\2014-15skaters.xlsx
./Stats\2014-15\2014-15skaters_adv.xlsx
./Stats\2014-15\2014-15skaters_misc.xlsx
./Stats\2015-16\2015-16goalies.xlsx
./Stats\2015-16\2015-16goalies_shootout.xlsx
./Stats\2015-16\2015-16skaters.xlsx
./Stats\2015-16\2015-16skaters_adv.xlsx
./Stats\2015-16\2015-16skaters_misc.xlsx
./Stats\2016-17\2016-17goalies.xlsx
./Stats\2016-17\2016-17goalies_shootout.xlsx
./Stats\2016-17\2016-17skaters.xlsx
./Stats\2016-17\2016-17skaters_adv.xlsx
./Stats\2016-17\2016-17skaters_misc.xlsx
./Stats\2017-18\2017-18goalie.xlsx
./Stats\2017-18\2017-18goalie_shootout.xlsx
./Stats\2017-18\2017-18skaters.xlsx
./Stats\2017-18\2017-18skaters_misc.xlsx
./Stats\2017-18\2017-18skaters_shootout.xlsx
./Stats\2018-19\2018-19goalie.xlsx
./Stats\2018-19\2018-19goalie_shootout.xlsx
./Stats\2018-19\2018-19skaters.xlsx
./Stats\2018-19\2018-19skaters_adv.xlsx
./Stats\2018-19\2018-19skaters_misc.xlsx
./Stats\2018-19\2018-19skaters_shootout.xlsx
./Stats\2019-20\2019-20goalies.xlsx
./Stats\2019-20\2019-20goalie_shootout.xlsx
./Stats\2019-20\2019-20skaters.xlsx
./Stats\2019-20\2019-20skaters_adv.xlsx
./Stats\2019-20\2019-20skaters_misc.xlsx
./Stats\2019-20\2019-20skaters_shootout.xlsx
./Stats\2020-21\2020-21goalies.xlsx
./Stats\2020-21\2020-21goalie_shootout.xlsx
./Stats\2020-21\2020-21skaters.xlsx
./Stats\2020-21\2020-21skaters_adv.xlsx
./Stats\2020-21\2020-21skaters_shootout.xlsx
./Stats\2020-21\2020-21skater_misc.xlsx

In [3]:
files_xlsx= [f for f in xl_list if f[-4:] == "xlsx"]
files_xlsx

['./Stats\\2007-08\\2007-08goalies.xlsx',
 './Stats\\2007-08\\2007-08skaters.xlsx',
 './Stats\\2007-08\\2007-08skaters_adv.xlsx',
 './Stats\\2008-09\\2008-09goalies.xlsx',
 './Stats\\2008-09\\2008-09goalies_shootout.xlsx',
 './Stats\\2008-09\\2008-09skaters.xlsx',
 './Stats\\2008-09\\2008-09skaters_adv.xlsx',
 './Stats\\2008-09\\2008-09skaters_shootout.xlsx',
 './Stats\\2009-10\\2009-10goalies.xlsx',
 './Stats\\2009-10\\2009-10goalies_shootout.xlsx',
 './Stats\\2009-10\\2009-10skaters.xlsx',
 './Stats\\2009-10\\2009-10skaters_adv.xlsx',
 './Stats\\2009-10\\2009-10skaters_shootout.xlsx',
 './Stats\\2010-11\\2010-11goalies.xlsx',
 './Stats\\2010-11\\2010-11goalies_shootout.xlsx',
 './Stats\\2010-11\\2010-11skaters.xlsx',
 './Stats\\2010-11\\2010-11skaters_adv.xlsx',
 './Stats\\2010-11\\2010-11skaters_shootout.xlsx',
 './Stats\\2011-12\\2011-12goalies.xlsx',
 './Stats\\2011-12\\2011-12goalies_shootout.xlsx',
 './Stats\\2011-12\\2011-12skaters.xlsx',
 './Stats\\2011-12\\2011-12skaters_adv.xlsx',
 './Stats\\2011-12\\2011-12skaters_shootout.xlsx',
 './Stats\\2012-13\\2012-13goalies.xlsx',
 './Stats\\2012-13\\2012-13goalies_shootout.xlsx',
 './Stats\\2012-13\\2012-13skaters.xlsx',
 './Stats\\2012-13\\2012-13skaters_adv.xlsx',
 './Stats\\2012-13\\2012-13skaters_shootout.xlsx',
 './Stats\\2013-14\\2013-14goalies.xlsx',
 './Stats\\2013-14\\2013-14goalies_shootout.xlsx',
 './Stats\\2013-14\\2013-14skaters.xlsx',
 './Stats\\2013-14\\2013-14skaters_adv.xlsx',
 './Stats\\2013-14\\2013-14skaters_shootout.xlsx',
 './Stats\\2014-15\\2014-15goalies.xlsx',
 './Stats\\2014-15\\2014-15goalies_shootout.xlsx',
 './Stats\\2014-15\\2014-15skaters.xlsx',
 './Stats\\2014-15\\2014-15skaters_adv.xlsx',
 './Stats\\2014-15\\2014-15skaters_misc.xlsx',
 './Stats\\2015-16\\2015-16goalies.xlsx',
 './Stats\\2015-16\\2015-16goalies_shootout.xlsx',
 './Stats\\2015-16\\2015-16skaters.xlsx',
 './Stats\\2015-16\\2015-16skaters_adv.xlsx',
 './Stats\\2015-16\\2015-16skaters_misc.xlsx',
 './Stats\\2016-17\\2016-17goalies.xlsx',
 './Stats\\2016-17\\2016-17goalies_shootout.xlsx',
 './Stats\\2016-17\\2016-17skaters.xlsx',
 './Stats\\2016-17\\2016-17skaters_adv.xlsx',
 './Stats\\2016-17\\2016-17skaters_misc.xlsx',
 './Stats\\2017-18\\2017-18goalie.xlsx',
 './Stats\\2017-18\\2017-18goalie_shootout.xlsx',
 './Stats\\2017-18\\2017-18skaters.xlsx',
 './Stats\\2017-18\\2017-18skaters_misc.xlsx',
 './Stats\\2017-18\\2017-18skaters_shootout.xlsx',
 './Stats\\2018-19\\2018-19goalie.xlsx',
 './Stats\\2018-19\\2018-19goalie_shootout.xlsx',
 './Stats\\2018-19\\2018-19skaters.xlsx',
 './Stats\\2018-19\\2018-19skaters_adv.xlsx',
 './Stats\\2018-19\\2018-19skaters_misc.xlsx',
 './Stats\\2018-19\\2018-19skaters_shootout.xlsx',
 './Stats\\2019-20\\2019-20goalies.xlsx',
 './Stats\\2019-20\\2019-20goalie_shootout.xlsx',
 './Stats\\2019-20\\2019-20skaters.xlsx',
 './Stats\\2019-20\\2019-20skaters_adv.xlsx',
 './Stats\\2019-20\\2019-20skaters_misc.xlsx',
 './Stats\\2019-20\\2019-20skaters_shootout.xlsx',
 './Stats\\2020-21\\2020-21goalies.xlsx',
 './Stats\\2020-21\\2020-21goalie_shootout.xlsx',
 './Stats\\2020-21\\2020-21skaters.xlsx',
 './Stats\\2020-21\\2020-21skaters_adv.xlsx',
 './Stats\\2020-21\\2020-21skaters_shootout.xlsx',
 './Stats\\2020-21\\2020-21skater_misc.xlsx']

In [5]:
def goalie_cleaner(g_file):
    goalies= g_file.T
    goalies= goalies.set_index(0)
    goalies= goalies.T
    goalies= goalies.set_index('Player')
    goalies= goalies.drop(columns=['Rk','GSAA','GA%-','QS%'])
    goalies= goalies.rename(columns={'SO':'SUT'})
    return(goalies)

def g_SOT_cleaner (g_file2):
    g= g_file2.set_index('Player')
    g= g.rename(columns={'Att.':'SOT_Att','Made':'SOT_Scored','Miss':'SOT_Saved','Pct.':'SOT_Pct'})
    return (g)
    
    #then goalies_0809= pd.merge(g0809,g_shootout_0809,how='inner', on='Player')
    #then add the year g['season']=200x
    
def fix_tot(file):
    tot= file.loc[(slice(None),'TOT'),:]

#               ***GOALIE DATA FOR 2008-2009 SEASON***

In [6]:
g0809=pd.DataFrame()
g0809= pd.read_excel('./Stats/2008-09/2008-09goalies.xlsx', engine= 'openpyxl')

gs_0809=pd.DataFrame()
gs_0809= pd.read_excel('./Stats/2008-09/2008-09goalies_shootout.xlsx', engine= 'openpyxl')

g0809=goalie_cleaner(g0809)
gs_0809= g_SOT_cleaner(gs_0809)

goalies0809= pd.merge(g0809,gs_0809,how='left', on='Player')

goalies0809['Season']=2008
goalies0809= goalies0809.reset_index()
goalies0809= goalies0809.set_index(['Player', 'Season'])
goalies0809= goalies0809.drop(columns='Team')

goalies0809= goalies0809[goalies0809.index.get_level_values('Player') != 'Player']

replace_nulls= goalies0809[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies0809[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies0809= goalies0809.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies0809=goalies0809.reset_index()

### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies0809.Player.unique()

for player in uniqueplayers:
    x= goalies0809[goalies0809.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies0809= new_df.reset_index(drop=True)

goalies0809

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Craig Anderson,2008,27,FLA,31,27,15,7,5,74,...,16,6,0,1,1,2,11,7,4,36.4
1,Alex Auld,2008,28,OTT,43,38,16,18,7,101,...,22,4,0,0,0,2,25,9,16,64.0
2,Niklas Backstrom,2008,30,MIN,71,71,37,24,8,159,...,47,9,0,0,0,6,21,5,16,76.2
3,Martin Biron,2008,31,PHI,55,53,29,19,5,146,...,29,7,0,4,4,0,17,5,12,70.6
4,Ben Bishop,2008,22,STL,6,3,1,1,1,12,...,1,0,0,0,0,0,4,2,2,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,Steve Valiquette,2008,31,NYR,15,12,5,5,2,39,...,7,1,0,1,1,2,12,3,9,75.0
85,Semyon Varlamov,2008,20,WSH,6,5,4,0,1,13,...,4,1,0,0,0,2,0,0,0,0.0
86,Tomas Vokoun,2008,32,FLA,59,55,26,23,6,138,...,33,4,0,1,1,2,19,6,13,68.4
87,Cam Ward,2008,24,CAR,68,68,39,23,5,160,...,43,10,0,1,1,4,19,7,12,63.2
88,Kevin Weekes,2008,33,NJD,16,13,7,5,0,32,...,8,1,0,0,0,0,6,2,4,66.7

In [7]:
missing = pd.concat([goalies0809.isnull().sum(), 100 * goalies0809.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [8]:
goalies0809.to_csv('./Clean/goalies2008.csv')

#               ***GOALIE DATA FOR 2009-2010 SEASON***

In [9]:


g0910=pd.DataFrame()
g0910= pd.read_excel('./Stats/2009-10/2009-10goalies.xlsx', engine= 'openpyxl')
g0910

g_shootout_0910=pd.DataFrame()
g_shootout_0910= pd.read_excel('./Stats/2009-10/2009-10goalies_shootout.xlsx', engine= 'openpyxl')
g_shootout_0910

g0910= goalie_cleaner(g0910)

g_shootout_0910= g_SOT_cleaner(g_shootout_0910)

goalies0910= pd.merge(g0910,g_shootout_0910,how='left', on='Player')

goalies0910

goalies0910['Season']=2009
goalies0910

goalies0910= goalies0910.reset_index()

goalies0910= goalies0910.set_index(['Player', 'Season'])

goalies0910= goalies0910[goalies0910.index.get_level_values('Player') != 'Player']

replace_nulls= goalies0910[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies0910[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies0910= goalies0910.drop(columns='Team')

goalies0910= goalies0910.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies0910=goalies0910.reset_index()

### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies0910.Player.unique()

for player in uniqueplayers:
    x= goalies0910[goalies0910.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies0910= new_df.reset_index(drop=True)

goalies0910

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Craig Anderson,2009,28,COL,71,71,38,25,7,186,...,41,10,0,3,3,16,52,16,36,69.2
1,Alex Auld,2009,29,TOT,24,20,9,7,3,64,...,8,4,0,2,2,2,15,2,13,86.7
2,Johan Backlund,2009,28,PHI,1,1,0,1,0,2,...,1,0,0,0,0,0,0,0,0,0.0
3,Niklas Backstrom,2009,31,MIN,60,58,26,23,8,158,...,31,13,0,1,1,4,38,14,24,63.2
4,Jonathan Bernier,2009,21,LAK,3,3,3,0,0,4,...,2,0,0,1,1,0,6,0,6,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,Steve Valiquette,2009,32,NYR,6,5,2,3,0,19,...,2,2,0,0,0,0,0,0,0,0.0
79,Semyon Varlamov,2009,21,WSH,26,23,15,4,6,65,...,11,3,0,1,1,0,33,9,24,72.7
80,Tomas Vokoun,2009,33,FLA,63,62,23,28,11,157,...,38,6,0,2,2,0,49,19,30,61.2
81,Cam Ward,2009,25,CAR,47,44,18,23,5,119,...,25,4,0,3,3,0,13,7,6,46.2
82,Matt Zaba,2009,26,NYR,1,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0.0

In [10]:
missing = pd.concat([goalies0910.isnull().sum(), 100 * goalies0910.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [37]:
goalies0910.to_csv('./Clean/goalies2009.csv')

#              ***GOALIE DATA FOR 2010-2011 SEASON***

In [13]:
g1011=pd.DataFrame()
g1011= pd.read_excel('./Stats/2010-11/2010-11goalies.xlsx', engine= 'openpyxl')

gs_1011=pd.DataFrame()
gs_1011= pd.read_excel('./Stats/2010-11/2010-11goalies_shootout.xlsx', engine= 'openpyxl')


g1011=goalie_cleaner(g1011)
gs_1011= g_SOT_cleaner(gs_1011)

goalies1011= pd.merge(g1011,gs_1011,how='left', on='Player')

goalies1011['Season']=2010
goalies1011= goalies1011.reset_index()
goalies1011= goalies1011.set_index(['Player', 'Season'])
goalies1011= goalies1011.drop(columns='Team')

goalies1011= goalies1011[goalies1011.index.get_level_values('Player') != 'Player']

replace_nulls= goalies1011[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies1011[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies1011= goalies1011.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies1011=goalies1011.reset_index()

### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies1011.Player.unique()

for player in uniqueplayers:
    x= goalies1011[goalies1011.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies1011= new_df.reset_index(drop=True)

goalies1011

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Craig Anderson,2010,29,TOT,51,49,24,20,4,135,...,29,10,0,1,1,4,15,1,14,93.3
1,Alex Auld,2010,30,MTL,16,12,6,2,2,33,...,6,2,0,1,1,2,4,1,3,75.0
2,Richard Bachman,2010,23,DAL,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
3,Niklas Backstrom,2010,32,MIN,51,50,22,23,5,132,...,29,9,0,1,1,2,17,8,9,52.9
4,Jonathan Bernier,2010,22,LAK,25,22,11,8,3,57,...,14,5,0,0,0,0,5,3,2,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Tim Thomas,2010,36,BOS,57,55,35,11,9,112,...,41,3,0,3,3,13,19,9,10,52.6
83,Marty Turco,2010,35,CHI,29,27,11,11,3,82,...,10,5,0,0,0,6,13,7,6,46.2
84,Semyon Varlamov,2010,22,WSH,27,25,11,9,5,58,...,18,2,0,0,0,2,8,3,5,62.5
85,Tomas Vokoun,2010,34,FLA,57,57,22,28,5,137,...,31,8,0,1,1,2,13,2,11,84.6
86,Cam Ward,2010,26,CAR,74,73,37,26,10,184,...,43,8,0,1,1,0,25,6,19,76.0

In [19]:
missing = pd.concat([goalies1011.isnull().sum(), 100 * goalies1011.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [38]:
goalies1011.to_csv('./Clean/goalies2010.csv')

#               ***GOALIE DATA FOR 2011-2012 SEASON***

In [24]:
g1112=pd.DataFrame()
g1112= pd.read_excel('./Stats/2011-12/2011-12goalies.xlsx', engine= 'openpyxl')

gs_1112=pd.DataFrame()
gs_1112= pd.read_excel('./Stats/2011-12/2011-12goalies_shootout.xlsx', engine= 'openpyxl')


g1112=goalie_cleaner(g1112)
gs_1112= g_SOT_cleaner(gs_1112)

goalies1112= pd.merge(g1112,gs_1112,how='left', on='Player')

goalies1112['Season']=2011
goalies1112= goalies1112.reset_index()
goalies1112= goalies1112.set_index(['Player', 'Season'])
goalies1112= goalies1112.drop(columns='Team')

goalies1112= goalies1112[goalies1112.index.get_level_values('Player') != 'Player']


replace_nulls= goalies1112[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies1112[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies1112= goalies1112.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies1112=goalies1112.reset_index()

### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies1112.Player.unique()

for player in uniqueplayers:
    x= goalies1112[goalies1112.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies1112= new_df.reset_index(drop=True)

### single null value found in SV_Pct column, was for a player who only dressed one game. thus we can drop this row altogether
goalies1112= goalies1112[~goalies1112.SV_Pct.isnull()]


goalies1112

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Craig Anderson,2011,30,OTT,63,60,33,22,6,165,...,34,9,0,4,4,4,25,7,18,72.0
1,Alex Auld,2011,31,OTT,14,8,2,4,2,36,...,2,2,0,0,0,0,4,3,1,25.0
2,Richard Bachman,2011,24,DAL,18,15,8,5,1,43,...,9,2,0,1,1,0,3,1,2,66.7
3,Niklas Backstrom,2011,33,MIN,46,45,19,18,7,105,...,24,8,0,2,2,2,32,15,17,53.1
4,Jonathan Bernier,2011,23,LAK,16,13,5,6,2,35,...,6,1,0,0,0,0,2,2,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,Marty Turco,2011,36,BOS,5,4,2,2,0,16,...,1,2,0,0,0,2,0,0,0,0.0
85,Semyon Varlamov,2011,23,COL,53,52,26,24,3,136,...,28,10,0,1,1,2,24,2,22,91.7
86,Tomas Vokoun,2011,35,WSH,48,46,25,17,2,108,...,23,8,0,2,2,4,4,2,2,50.0
87,Cam Ward,2011,27,CAR,68,68,30,23,13,182,...,38,10,1,0,1,4,14,6,8,57.1
88,Allen York,2011,22,CBJ,11,5,3,2,0,16,...,3,0,0,0,0,0,0,0,0,0.0

In [25]:
missing = pd.concat([goalies1112.isnull().sum(), 100 * goalies1112.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [26]:
goalies1112.to_csv('./Clean/goalies2011.csv')

 #               ***GOALIE DATA FOR 2012-2013 SEASON***

In [27]:
g1213=pd.DataFrame()
g1213= pd.read_excel('./Stats/2012-13/2012-13goalies.xlsx', engine= 'openpyxl')

gs_1213=pd.DataFrame()
gs_1213= pd.read_excel('./Stats/2012-13/2012-13goalies_shootout.xlsx', engine= 'openpyxl')


g1213=goalie_cleaner(g1213)
gs_1213= g_SOT_cleaner(gs_1213)

goalies1213= pd.merge(g1213,gs_1213,how='left', on='Player')

goalies1213['Season']=2012
goalies1213= goalies1213.reset_index()
goalies1213= goalies1213.set_index(['Player', 'Season'])
goalies1213= goalies1213.drop(columns='Team')

goalies1213= goalies1213[goalies1213.index.get_level_values('Player') != 'Player']

replace_nulls= goalies1213[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies1213[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies1213= goalies1213.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies1213=goalies1213.reset_index()

### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies1213.Player.unique()

for player in uniqueplayers:
    x= goalies1213[goalies1213.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies1213= new_df.reset_index(drop=True)

goalies1213

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Sami Aittokallio,2012,20,COL,1,1,0,0,0,2,...,1,0,0,0,0,0,0,0,0,0.0
1,Jake Allen,2012,22,STL,15,13,9,4,0,33,...,6,4,0,0,0,0,2,0,2,100.0
2,Craig Anderson,2012,31,OTT,24,24,12,9,2,40,...,17,1,0,0,0,0,3,3,0,0.0
3,Richard Bachman,2012,25,DAL,13,8,6,5,0,33,...,4,3,0,0,0,0,0,0,0,0.0
4,Niklas Backstrom,2012,34,MIN,42,41,24,15,3,98,...,18,8,0,0,0,2,15,8,7,46.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,Daniel Taylor,2012,26,CGY,2,2,1,1,0,6,...,1,0,0,0,0,0,0,0,0,0.0
78,Jose Theodore,2012,36,FLA,15,14,4,6,3,42,...,5,5,0,0,0,2,4,2,2,50.0
79,Semyon Varlamov,2012,24,COL,35,33,11,21,3,98,...,12,7,0,1,1,0,6,2,4,66.7
80,Tomas Vokoun,2012,36,PIT,20,17,13,4,0,42,...,9,5,0,2,2,2,0,0,0,0.0
81,Cam Ward,2012,28,CAR,17,16,9,6,1,44,...,8,3,0,0,0,0,0,0,0,0.0

In [28]:
missing = pd.concat([goalies1213.isnull().sum(), 100 * goalies1213.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [29]:
goalies1213.to_csv('./Clean/goalies2012.csv')

#               ***GOALIE DATA FOR 2013-2014 SEASON***

In [32]:
g1314=pd.DataFrame()
g1314= pd.read_excel('./Stats/2013-14/2013-14goalies.xlsx', engine= 'openpyxl')

gs_1314=pd.DataFrame()
gs_1314= pd.read_excel('./Stats/2013-14/2013-14goalies_shootout.xlsx', engine= 'openpyxl')

g1314=goalie_cleaner(g1314)
gs_1314= g_SOT_cleaner(gs_1314)

goalies_1314= pd.merge(g1314,gs_1314,how='inner', on='Player')

goalies_1314['Season']=2013
goalies_1314= goalies_1314.reset_index()
goalies_1314= goalies_1314.set_index(['Player', 'Season'])
goalies_1314= goalies_1314.drop(columns='Team')

goalies_1314= goalies_1314[goalies_1314.index.get_level_values('Player') != 'Player']

replace_nulls= goalies_1314[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies_1314[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies_1314= goalies_1314.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies_1314=goalies_1314.reset_index()

### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies_1314.Player.unique()

for player in uniqueplayers:
    x= goalies_1314[goalies_1314.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies_1314= new_df.reset_index(drop=True)

goalies_1314

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Frederik Andersen,2013,24,ANA,28,24,20,5,0,60,...,12,0,0,1,1,0,4,0,4,100.0
1,Craig Anderson,2013,32,OTT,53,52,25,16,8,150,...,26,10,0,1,1,2,15,5,10,66.7
2,Richard Bachman,2013,26,EDM,3,3,0,2,1,7,...,1,2,0,0,0,0,3,2,1,33.3
3,Niklas Backstrom,2013,35,MIN,21,19,5,11,2,55,...,9,3,0,0,0,0,6,3,3,50.0
4,Jonathan Bernier,2013,25,TOR,55,49,26,19,7,139,...,30,5,0,1,1,4,25,9,16,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Tim Thomas,2013,39,TOT,48,45,18,24,4,128,...,25,7,0,1,1,4,33,8,25,75.8
70,Dustin Tokarski,2013,24,MTL,3,2,2,0,0,5,...,2,0,0,0,0,0,6,2,4,66.7
71,Semyon Varlamov,2013,25,COL,63,60,41,14,6,146,...,44,4,0,3,3,2,23,7,16,69.6
72,Cam Ward,2013,29,CAR,30,28,10,12,6,84,...,11,6,0,1,1,2,8,3,5,62.5
73,Jeff Zatkoff,2013,26,PIT,20,18,12,6,2,51,...,9,3,0,1,1,0,4,2,2,50.0

In [33]:
missing = pd.concat([goalies_1314.isnull().sum(), 100 * goalies_1314.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [39]:
goalies_1314.to_csv('./Clean/goalies2013.csv')

#               ***GOALIE DATA FOR 2014-2015 SEASON***

In [55]:
g1415=pd.DataFrame()
g1415= pd.read_excel('./Stats/2014-15/2014-15goalies.xlsx', engine= 'openpyxl')

gs_1415=pd.DataFrame()
gs_1415= pd.read_excel('./Stats/2014-15/2014-15goalies_shootout.xlsx', engine= 'openpyxl')

g1415=goalie_cleaner(g1415)
gs_1415= g_SOT_cleaner(gs_1415)

goalies_1415= pd.merge(g1415,gs_1415,how='inner', on='Player')

goalies_1415['Season']=2014
goalies_1415= goalies_1415.reset_index()
goalies_1415= goalies_1415.set_index(['Player', 'Season'])
goalies_1415= goalies_1415.drop(columns='Team')

goalies_1415= goalies_1415[goalies_1415.index.get_level_values('Player') != 'Player']

replace_nulls= goalies_1415[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies_1415[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies_1415= goalies_1415.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies_1415=goalies_1415.reset_index()

### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies_1415.Player.unique()

for player in uniqueplayers:
    x= goalies_1415[goalies_1415.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies_1415= new_df.reset_index(drop=True)

goalies_1415

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Jake Allen,2014,24,STL,37,32,22,7,4,79,...,17,6,0,2,2,2,15,4,11,73.3
1,Frederik Andersen,2014,25,ANA,54,53,35,12,5,123,...,32,9,0,3,3,4,32,11,21,65.6
2,Craig Anderson,2014,33,OTT,35,35,14,13,8,87,...,17,2,0,0,0,4,20,6,14,70.0
3,Richard Bachman,2014,27,EDM,6,4,3,2,0,15,...,3,1,0,0,0,0,2,0,2,100.0
4,Niklas Backstrom,2014,36,MIN,19,14,5,7,3,51,...,2,4,0,0,0,2,6,2,4,66.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,Cam Talbot,2014,27,NYR,36,34,21,9,4,77,...,17,2,0,0,0,0,11,5,6,54.5
67,Dustin Tokarski,2014,25,MTL,17,16,6,6,4,46,...,8,1,0,1,1,0,23,9,14,60.9
68,Semyon Varlamov,2014,26,COL,57,57,28,20,8,141,...,33,6,0,0,0,4,33,10,23,69.7
69,Cam Ward,2014,30,CAR,51,50,22,24,5,121,...,26,7,0,0,0,4,24,7,17,70.8
70,Rob Zepp,2014,33,PHI,10,9,5,2,0,25,...,1,2,0,0,0,0,2,0,2,100.0

In [53]:
missing = pd.concat([goalies_1415.isnull().sum(), 100 * goalies_1415.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [47]:
goalies_1415.to_csv('./Clean/goalies2014.csv')

#               ***GOALIE DATA FOR 2015-2016 SEASON***

In [54]:
g1516=pd.DataFrame()
g1516= pd.read_excel('./Stats/2015-16/2015-16goalies.xlsx', engine= 'openpyxl')

gs_1516=pd.DataFrame()
gs_1516= pd.read_excel('./Stats/2015-16/2015-16goalies_shootout.xlsx', engine= 'openpyxl')

g1516=goalie_cleaner(g1516)
gs_1516= g_SOT_cleaner(gs_1516)

goalies_1516= pd.merge(g1516,gs_1516,how='inner', on='Player')

goalies_1516['Season']=2015
goalies_1516= goalies_1516.reset_index()
goalies_1516= goalies_1516.set_index(['Player', 'Season'])
goalies_1516= goalies_1516.drop(columns='Team')

goalies_1516= goalies_1516[goalies_1516.index.get_level_values('Player') != 'Player']

replace_nulls= goalies_1516[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies_1516[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies_1516= goalies_1516.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies_1516.Player.unique()

for player in uniqueplayers:
    x= goalies_1516[goalies_1516.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies_1516= new_df.reset_index(drop=True)

goalies_1516

AttributeError: 'DataFrame' object has no attribute 'Player'

In [61]:
g1516=pd.DataFrame()
g1516= pd.read_excel('./Stats/2014-15/2014-15goalies.xlsx', engine= 'openpyxl')

gs_1516=pd.DataFrame()
gs_1516= pd.read_excel('./Stats/2014-15/2014-15goalies_shootout.xlsx', engine= 'openpyxl')

g1516=goalie_cleaner(g1516)
gs_1516= g_SOT_cleaner(gs_1516)

goalies_1516= pd.merge(g1516,gs_1516,how='inner', on='Player')

goalies_1516['Season']=2014
goalies_1516= goalies_1516.reset_index()
goalies_1516= goalies_1516.set_index(['Player', 'Season'])
goalies_1516= goalies_1516.drop(columns='Team')

goalies_1516= goalies_1516[goalies_1516.index.get_level_values('Player') != 'Player']

replace_nulls= goalies_1516[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies_1516[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies_1516= goalies_1516.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies_1516=goalies_1516.reset_index()

### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies_1516.Player.unique()

for player in uniqueplayers:
    x= goalies_1516[goalies_1516.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies_1516= new_df.reset_index(drop=True)

goalies_1516

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Jake Allen,2014,24,STL,37,32,22,7,4,79,...,17,6,0,2,2,2,15,4,11,73.3
1,Frederik Andersen,2014,25,ANA,54,53,35,12,5,123,...,32,9,0,3,3,4,32,11,21,65.6
2,Craig Anderson,2014,33,OTT,35,35,14,13,8,87,...,17,2,0,0,0,4,20,6,14,70.0
3,Richard Bachman,2014,27,EDM,6,4,3,2,0,15,...,3,1,0,0,0,0,2,0,2,100.0
4,Niklas Backstrom,2014,36,MIN,19,14,5,7,3,51,...,2,4,0,0,0,2,6,2,4,66.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,Cam Talbot,2014,27,NYR,36,34,21,9,4,77,...,17,2,0,0,0,0,11,5,6,54.5
67,Dustin Tokarski,2014,25,MTL,17,16,6,6,4,46,...,8,1,0,1,1,0,23,9,14,60.9
68,Semyon Varlamov,2014,26,COL,57,57,28,20,8,141,...,33,6,0,0,0,4,33,10,23,69.7
69,Cam Ward,2014,30,CAR,51,50,22,24,5,121,...,26,7,0,0,0,4,24,7,17,70.8
70,Rob Zepp,2014,33,PHI,10,9,5,2,0,25,...,1,2,0,0,0,0,2,0,2,100.0

In [62]:
missing = pd.concat([goalies_1516.isnull().sum(), 100 * goalies_1516.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [63]:
goalies_1516.to_csv('./Clean/goalies2015.csv')

#               ***GOALIE DATA FOR 2016-2017 SEASON***

In [64]:
g1617=pd.DataFrame()
g1617= pd.read_excel('./Stats/2016-17/2016-17goalies.xlsx', engine= 'openpyxl')

gs_1617=pd.DataFrame()
gs_1617= pd.read_excel('./Stats/2016-17/2016-17goalies_shootout.xlsx', engine= 'openpyxl')

g1617=goalie_cleaner(g1617)
gs_1617= g_SOT_cleaner(gs_1617)

goalies_1617= pd.merge(g1617,gs_1617,how='inner', on='Player')

goalies_1617['Season']=2016
goalies_1617= goalies_1617.reset_index()
goalies_1617= goalies_1617.set_index(['Player', 'Season'])
goalies_1617= goalies_1617.drop(columns='Team')

goalies_1617= goalies_1617[goalies_1617.index.get_level_values('Player') != 'Player']

replace_nulls= goalies_1617[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies_1617[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies_1617= goalies_1617.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies_1617=goalies_1617.reset_index()

### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies_1617.Player.unique()

for player in uniqueplayers:
    x= goalies_1617[goalies_1617.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies_1617= new_df.reset_index(drop=True)

goalies_1617

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Jake Allen,2016,26,STL,61,60,33,20,5,138,...,33,11,0,1,1,4,15,4,11,73.3
1,Frederik Andersen,2016,27,TOR,66,66,33,16,14,169,...,38,11,0,1,1,16,23,11,12,52.2
2,Craig Anderson,2016,35,OTT,40,40,25,11,4,92,...,25,4,0,1,1,0,24,5,19,79.2
3,Jonathan Bernier,2016,28,ANA,39,33,21,7,4,83,...,19,4,0,0,0,4,33,11,22,66.7
4,Ben Bishop,2016,30,TOT,39,37,18,15,5,94,...,19,6,0,0,0,10,28,8,20,71.4
5,Sergei Bobrovsky,2016,28,CBJ,63,63,41,17,5,127,...,41,5,0,0,0,8,5,2,3,60.0
6,Peter Budaj,2016,34,TOT,60,55,30,21,3,120,...,32,7,0,1,1,0,13,7,6,46.2
7,Mike Condon,2016,26,TOT,41,38,19,14,6,96,...,19,7,0,0,0,4,13,3,10,76.9
8,Jared Coreau,2016,25,DET,14,14,5,4,3,41,...,5,6,0,0,0,0,3,1,2,66.7
9,Corey Crawford,2016,32,CHI,55,55,32,18,4,138,...,29,7,0,1,1,2,14,2,12,85.7
10,Scott Darling,2016,28,CHI,32,27,18,5,5,67,...,17,1,0,0,0,0,3,1,2,66.7
11,Louis Domingue,2016,24,ARI,31,26,11,15,1,82,...,12,4,0,0,0,0,15,1,14,93.3
12,Devan Dubnyk,2016,30,MIN,65,63,40,19,5,141,...,39,7,0,0,0,10,20,7,13,65.0
13,Brian Elliott,2016,31,CGY,49,45,26,18,3,121,...,26,4,0,0,0,4,12,2,10,83.3
14,Jhonas Enroth,2016,28,TOR,6,4,0,3,1,18,...,0,0,0,0,0,0,3,1,2,66.7
15,Marc-Andre Fleury,2016,32,PIT,38,34,18,10,7,107,...,16,5,0,0,0,6,15,7,8,53.3
16,John Gibson,2016,23,ANA,52,49,25,16,9,109,...,28,7,0,1,1,4,9,2,7,77.8
17,Thomas Greiss,2016,31,NYI,51,49,26,18,5,126,...,30,11,0,1,1,0,19,8,11,57.9
18,Philipp Grubauer,2016,25,WSH,24,19,13,6,2,43,...,13,1,0,0,0,0,2,0,2,100.0
19,Jaroslav Halak,2016,31,NYI,28,26,12,9,5,75,...,14,3,0,1,1,0,8,3,5,62.5
20,Connor Hellebuyck,2016,23,WPG,56,53,26,19,4,146,...,25,9,0,0,0,0,16,4,12,75.0
21,Braden Holtby,2016,27,WSH,63,63,42,13,6,127,...,39,8,0,0,0,0,22,11,11,50.0
22,Jimmy Howard,2016,32,DET,26,24,10,11,1,49,...,16,4,0,0,0,2,6,1,5,83.3
23,Carter Hutton,2016,31,STL,30,21,13,8,2,58,...,11,3,0,1,1,4,4,1,3,75.0
24,Chad Johnson,2016,30,CGY,36,36,18,15,1,87,...,18,7,0,0,0,0,10,2,8,80.0
25,Martin Jones,2016,27,SJS,65,65,35,23,6,152,...,39,8,0,0,0,0,9,2,7,77.8
26,Anton Khudobin,2016,30,BOS,16,14,7,6,1,39,...,5,2,0,1,1,2,3,1,2,66.7
27,Keith Kinkaid,2016,27,NJD,26,23,8,13,3,65,...,12,4,0,1,1,0,5,1,4,80.0
28,Eddie Lack,2016,29,CAR,20,18,8,7,3,48,...,9,3,0,0,0,0,3,1,2,66.7
29,Robin Lehner,2016,25,BUF,59,58,23,26,8,152,...,32,6,0,1,1,6,8,8,0,0.0
30,Kari Lehtonen,2016,33,DAL,59,52,22,25,7,151,...,27,12,0,1,1,4,11,5,6,54.5
31,Henrik Lundqvist,2016,34,NYR,57,55,31,20,4,148,...,32,8,0,1,1,0,18,8,10,55.6
32,Roberto Luongo,2016,37,FLA,40,39,17,15,6,104,...,21,1,0,1,1,4,22,8,14,63.6
33,Jacob Markstrom,2016,27,VAN,26,23,10,11,3,62,...,12,2,0,0,0,2,9,1,8,88.9
34,Steve Mason,2016,28,PHI,58,54,26,21,8,143,...,26,11,0,1,1,0,36,8,28,77.8
35,Curtis McElhinney,2016,33,TOT,21,15,8,8,2,51,...,9,0,0,0,0,0,5,1,4,80.0
36,Ryan Miller,2016,36,VAN,54,54,18,29,6,150,...,26,7,0,1,1,22,10,2,8,80.0
37,Al Montoya,2016,31,MTL,19,18,8,6,4,50,...,12,2,0,2,2,2,6,3,3,50.0
38,Petr Mrazek,2016,24,DET,50,44,18,21,9,145,...,19,9,0,0,0,2,30,4,26,86.7
39,Matt Murray,2016,22,PIT,49,47,32,10,4,111,...,26,4,0,2,2,0,9,3,6,66.7
40,Michal Neuvirth,2016,28,PHI,28,24,11,11,1,64,...,10,4,0,0,0,2,6,0,6,100.0
41,Anders Nilsson,2016,26,BUF,26,23,10,10,4,66,...,11,2,0,0,0,0,18,6,12,66.7
42,Calvin Pickard,2016,24,COL,50,48,15,31,2,140,...,21,11,0,2,2,2,4,1,3,75.0
43,Carey Price,2016,29,MTL,62,62,37,20,5,138,...,38,8,0,1,1,4,11,3,8,72.7
44,Jonathan Quick,2016,31,LAK,17,17,8,5,2,35,...,11,2,0,0,0,2,3,0,3,100.0
45,Antti Raanta,2016,27,NYR,30,26,16,8,2,61,...,18,1,0,1,1,0,2,1,1,50.0
46,Tuukka Rask,2016,29,BOS,65,63,37,20,5,137,...,31,14,0,2,2,0,24,6,18,75.0
47,James Reimer,2016,28,FLA,43,39,18,16,5,98,...,19,4,0,0,0,2,14,4,10,71.4
48,Pekka Rinne,2016,34,NSH,61,61,31,19,9,144,...,34,7,0,0,0,4,15,4,11,73.3
49,Juuse Saros,2016,21,NSH,21,19,10,8,3,47,...,13,1,0,1,1,0,2,2,0,0.0
50,Cory Schneider,2016,30,NJD,60,59,20,27,11,163,...,27,7,0,0,0,0,11,3,8,72.7
51,Jeremy Smith,2016,27,COL,10,8,1,6,1,32,...,3,3,0,0,0,0,2,1,1,50.0
52,Mike Smith,2016,34,ARI,55,55,19,26,9,156,...,27,7,0,0,0,14,13,5,8,61.5
53,Anthony Stolarz,2016,23,PHI,7,4,2,1,1,13,...,2,1,0,0,0,0,3,2,1,33.3
54,Cam Talbot,2016,29,EDM,73,73,42,22,8,171,...,43,10,0,0,0,4,27,11,16,59.3
55,Andrei Vasilevskiy,2016,22,TBL,50,47,23,17,7,123,...,25,5,0,2,2,2,15,3,12,80.0
56,Cam Ward,2016,32,CAR,61,61,26,22,12,162,...,30,9,0,1,1,6,24,12,12,50.0

In [65]:
missing = pd.concat([goalies_1617.isnull().sum(), 100 * goalies_1617.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [71]:
goalies_1617.to_csv('./Clean/goalies2016.csv')

#               ***GOALIE DATA FOR 2017-2018 SEASON***

In [67]:


g1718=pd.DataFrame()
g1718= pd.read_excel('./Stats/2017-18/2017-18goalie.xlsx', engine= 'openpyxl')

gs_1718=pd.DataFrame()
gs_1718= pd.read_excel('./Stats/2017-18/2017-18goalie_shootout.xlsx', engine= 'openpyxl')

g1718=goalie_cleaner(g1718)
gs_1718= g_SOT_cleaner(gs_1718)

goalies_1718= pd.merge(g1718,gs_1718,how='inner', on='Player')

goalies_1718['Season']=2017
goalies_1718= goalies_1718.reset_index()
goalies_1718= goalies_1718.set_index(['Player', 'Season'])
goalies_1718= goalies_1718.drop(columns='Team')

goalies_1718= goalies_1718[goalies_1718.index.get_level_values('Player') != 'Player']

replace_nulls= goalies_1718[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies_1718[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies_1718= goalies_1718.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies_1718=goalies_1718.reset_index()

### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies_1718.Player.unique()

for player in uniqueplayers:
    x= goalies_1718[goalies_1718.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies_1718= new_df.reset_index(drop=True)

goalies_1718

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Jake Allen,2017,27,STL,59,56,27,25,3,152,...,27,8,0,1,1,0,2,0,2,100.0
1,Frederik Andersen,2017,28,TOR,66,66,38,21,5,182,...,37,8,0,1,1,2,33,7,26,78.8
2,Craig Anderson,2017,36,OTT,58,55,23,25,6,180,...,25,11,0,0,0,2,23,8,15,65.2
3,Jonathan Bernier,2017,29,COL,37,34,19,13,3,95,...,18,5,0,1,1,0,3,2,1,33.3
4,Reto Berra,2017,31,ANA,5,1,1,1,0,7,...,1,0,0,0,0,0,9,3,6,66.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Malcolm Subban,2017,24,VEG,22,19,13,4,2,55,...,8,2,0,0,0,2,13,0,13,100.0
57,Cam Talbot,2017,30,EDM,67,67,31,31,3,188,...,32,11,0,1,1,8,13,5,8,61.5
58,Semyon Varlamov,2017,29,COL,51,47,24,16,6,128,...,28,5,0,0,0,2,6,1,5,83.3
59,Andrei Vasilevskiy,2017,23,TBL,65,64,44,17,3,167,...,36,8,0,2,2,14,16,1,15,93.8
60,Cam Ward,2017,33,CAR,43,42,23,14,4,112,...,21,10,0,0,0,14,5,1,4,80.0

In [69]:
missing = pd.concat([goalies_1718.isnull().sum(), 100 * goalies_1718.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [73]:
goalies_1718.to_csv('./Clean/goalies2017.csv')

#               ***GOALIE DATA FOR 2018-2019 SEASON***

In [74]:

g1819=pd.DataFrame()
g1819= pd.read_excel('./Stats/2018-19/2018-19goalie.xlsx', engine= 'openpyxl')

gs_1819=pd.DataFrame()
gs_1819= pd.read_excel('./Stats/2018-19/2018-19goalie_shootout.xlsx', engine= 'openpyxl')

g1819=goalie_cleaner(g1819)
gs_1819= g_SOT_cleaner(gs_1819)

goalies_1819= pd.merge(g1819,gs_1819,how='inner', on='Player')

goalies_1819['Season']=2018
goalies_1819= goalies_1819.reset_index()
goalies_1819= goalies_1819.set_index(['Player', 'Season'])
goalies_1819= goalies_1819.drop(columns='Team')

goalies_1819= goalies_1819[goalies_1819.index.get_level_values('Player') != 'Player']

replace_nulls= goalies_1819[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies_1819[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies_1819= goalies_1819.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies_1819=goalies_1819.reset_index()


### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies_1819.Player.unique()

for player in uniqueplayers:
    x= goalies_1819[goalies_1819.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies_1819= new_df.reset_index(drop=True)

goalies_1819

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Jake Allen,2018,28,STL,46,45,19,17,8,121,...,25,11,0,0,0,0,8,5,3,37.5
1,Frederik Andersen,2018,29,TOR,60,60,36,16,7,162,...,38,7,0,1,1,2,9,3,6,66.7
2,Craig Anderson,2018,37,OTT,50,47,17,27,4,163,...,19,8,0,2,2,0,2,2,0,0.0
3,Jonathan Bernier,2018,30,DET,35,30,9,18,5,98,...,13,5,0,0,0,0,6,1,5,83.3
4,Jordan Binnington,2018,25,STL,32,30,24,5,1,59,...,20,1,0,0,0,0,11,1,10,90.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,Cam Talbot,2018,31,TOT,35,32,11,17,3,108,...,9,10,0,1,1,0,5,1,4,80.0
62,Linus Ullmark,2018,25,BUF,37,34,15,14,5,109,...,18,6,0,1,1,0,10,1,9,90.0
63,Semyon Varlamov,2018,30,COL,49,49,20,19,9,136,...,25,9,0,0,0,2,9,3,6,66.7
64,Andrei Vasilevskiy,2018,24,TBL,53,53,39,10,4,128,...,34,7,0,3,3,6,14,3,11,78.6
65,Cam Ward,2018,34,CHI,33,29,16,12,4,115,...,15,5,0,1,1,4,5,0,5,100.0

In [75]:
missing = pd.concat([goalies_1819.isnull().sum(), 100 * goalies_1819.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [76]:

goalies_1819.to_csv('./Clean/goalies2018.csv')

#               ***GOALIE DATA FOR 2019-2020 SEASON***

In [77]:
#               ***GOALIE DATA FOR 2017-2017 SEASON***

g1920=pd.DataFrame()
g1920= pd.read_excel('./Stats/2019-20/2019-20goalies.xlsx', engine= 'openpyxl')

gs_1920=pd.DataFrame()
gs_1920= pd.read_excel('./Stats/2019-20/2019-20goalie_shootout.xlsx', engine= 'openpyxl')

g1920=goalie_cleaner(g1920)
gs_1920= g_SOT_cleaner(gs_1920)

goalies_1920= pd.merge(g1920,gs_1920,how='inner', on='Player')

goalies_1920['Season']=2019
goalies_1920= goalies_1920.reset_index()
goalies_1920= goalies_1920.set_index(['Player', 'Season'])
goalies_1920= goalies_1920.drop(columns='Team')

goalies_1920= goalies_1920[goalies_1920.index.get_level_values('Player') != 'Player']

replace_nulls= goalies_1920[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies_1920[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies_1920= goalies_1920.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies_1920=goalies_1920.reset_index()



### remove duplicates due to trades
new_list=[]

uniqueplayers=goalies_1920.Player.unique()

for player in uniqueplayers:
    x= goalies_1920[goalies_1920.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies_1920= new_df.reset_index(drop=True)

goalies_1920

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Jake Allen,2019,29,STL,24,21,12,6,3,48,...,14,2,0,0,0,0,9,3,6,66.7
1,Frederik Andersen,2019,30,TOR,52,52,29,13,7,143,...,27,8,0,0,0,0,24,9,15,62.5
2,Jonathan Bernier,2019,31,DET,46,41,15,22,3,126,...,17,5,0,3,3,4,11,2,9,81.8
3,Jordan Binnington,2019,26,STL,50,50,30,13,7,126,...,28,5,0,1,1,4,10,3,7,70.0
4,Ben Bishop,2019,33,DAL,44,43,21,16,4,103,...,27,5,0,2,2,2,9,5,4,44.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Malcolm Subban,2019,26,TOT,21,19,9,7,3,60,...,7,7,0,0,0,0,3,1,2,66.7
59,Cam Talbot,2019,32,CGY,26,22,12,10,1,63,...,11,2,0,0,0,21,2,2,0,0.0
60,Linus Ullmark,2019,26,BUF,34,34,17,14,3,91,...,19,2,0,0,0,4,9,1,8,88.9
61,Semyon Varlamov,2019,31,NYI,45,39,19,14,6,110,...,21,4,0,0,0,0,12,4,8,66.7
62,Andrei Vasilevskiy,2019,25,TBL,52,52,35,14,3,133,...,31,7,0,4,4,4,11,2,9,81.8

In [78]:
missing = pd.concat([goalies_1920.isnull().sum(), 100 * goalies_1920.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [80]:

goalies_1920.to_csv('./Clean/goalies2019.csv')

In [81]:
#               ***GOALIE DATA FOR 2017-2017 SEASON***

g2021=pd.DataFrame()
g2021= pd.read_excel('./Stats/2020-21/2020-21goalies.xlsx', engine= 'openpyxl')

gs_2021=pd.DataFrame()
gs_2021= pd.read_excel('./Stats/2020-21/2020-21goalie_shootout.xlsx', engine= 'openpyxl')

g2021=goalie_cleaner(g2021)
gs_2021= g_SOT_cleaner(gs_2021)

goalies_2021= pd.merge(g2021,gs_2021,how='inner', on='Player')

goalies_2021['Season']=2020
goalies_2021= goalies_2021.reset_index()
goalies_2021= goalies_2021.set_index(['Player', 'Season'])
goalies_2021= goalies_2021.drop(columns='Team')

goalies_2021= goalies_2021[goalies_2021.index.get_level_values('Player') != 'Player']

replace_nulls= goalies_2021[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']].fillna (value=0)

goalies_2021[['SOT_Att','SOT_Scored','SOT_Saved','SOT_Pct']]= replace_nulls

goalies_2021= goalies_2021.rename(columns={'T/O':'TplusOTL','SV%':'SV_Pct'})

goalies_2021=goalies_2021.reset_index()

#### remove duplicates due to trades

new_list=[]

uniqueplayers=goalies_2021.Player.unique()

for player in uniqueplayers:
    x= goalies_2021[goalies_2021.Player == player]
    uni_t= x.Tm.unique()
    if 'TOT' in uni_t:
        x= x[x.Tm == 'TOT']
    new_list.append(x)
    
new_df= pd.concat(new_list)
goalies_2021= new_df.reset_index(drop=True)

goalies_2021

,Player,Season,Age,Tm,GP,GS,W,L,TplusOTL,GA,...,QS,RBS,G,A,PTS,PIM,SOT_Att,SOT_Scored,SOT_Saved,SOT_Pct
0,Jordan Binnington,2020,27,STL,42,41,18,14,8,108,...,21,5,0,1,1,2,15,6,9,60.0
1,Mackenzie Blackwood,2020,24,NJD,35,35,14,17,4,106,...,18,10,0,0,0,0,11,6,5,45.5
2,Sergei Bobrovsky,2020,32,FLA,31,30,19,8,2,88,...,16,4,0,0,0,0,10,4,6,60.0
3,Jack Campbell,2020,29,TOR,22,22,17,3,2,46,...,13,2,0,0,0,0,3,0,3,100.0
4,Thatcher Demko,2020,25,VAN,35,35,16,18,1,99,...,19,3,0,0,0,0,7,0,7,100.0
5,Casey DeSmith,2020,29,PIT,20,17,11,7,0,48,...,9,2,0,1,1,0,7,0,7,100.0
6,Chris Driedger,2020,26,FLA,23,23,14,6,3,47,...,15,3,0,2,2,0,4,1,3,75.0
7,Devan Dubnyk,2020,34,TOT,22,18,6,11,2,63,...,8,4,0,0,0,2,3,2,1,33.3
8,Brian Elliott,2020,35,PHI,30,26,15,9,2,82,...,12,8,0,1,1,0,8,2,6,75.0
9,Alexandar Georgiev,2020,24,NYR,19,18,8,7,2,44,...,9,3,0,1,1,0,3,1,2,66.7
10,John Gibson,2020,27,ANA,35,35,9,19,7,101,...,15,7,0,0,0,2,3,2,1,33.3
11,Thomas Greiss,2020,35,DET,34,29,8,15,8,79,...,17,4,0,0,0,2,25,10,15,60.0
12,Filip Gustavsson,2020,22,OTT,9,7,5,1,2,17,...,6,0,0,0,0,0,4,1,3,75.0
13,Jaroslav Halak,2020,35,BOS,19,17,9,6,4,46,...,9,3,0,0,0,0,5,2,3,60.0
14,Carter Hart,2020,22,PHI,27,25,9,11,5,89,...,9,8,0,0,0,2,17,6,11,64.7
15,Connor Hellebuyck,2020,27,WPG,45,45,24,17,3,112,...,25,6,0,0,0,0,6,3,3,50.0
16,Adin Hill,2020,24,ARI,19,17,9,9,1,46,...,8,2,0,0,0,0,5,2,3,60.0
17,Braden Holtby,2020,31,VAN,21,21,7,11,3,77,...,7,5,0,1,1,0,10,3,7,70.0
18,Michael Houser,2020,28,BUF,4,4,2,2,0,14,...,3,1,0,0,0,0,3,0,3,100.0
19,Tristan Jarry,2020,25,PIT,39,38,25,9,3,100,...,24,7,0,4,4,8,5,3,2,40.0
20,Jonas Johansson,2020,25,TOT,15,13,5,6,2,39,...,6,2,0,0,0,0,5,5,0,0.0
21,Martin Jones,2020,31,SJS,34,34,15,13,4,102,...,15,12,0,0,0,0,25,6,19,76.0
22,Anton Khudobin,2020,34,DAL,32,32,12,11,7,76,...,17,8,0,2,2,2,16,6,10,62.5
23,Joonas Korpisalo,2020,26,CBJ,33,31,9,13,7,96,...,13,8,0,1,1,2,10,4,6,60.0
24,Darcy Kuemper,2020,30,ARI,27,27,10,11,3,66,...,15,3,0,0,0,4,9,6,3,33.3
25,Kevin Lankinen,2020,25,CHI,37,37,17,14,5,109,...,19,5,0,2,2,2,9,2,7,77.8
26,Robin Lehner,2020,29,VEG,19,19,13,4,2,44,...,12,4,0,1,1,0,8,3,5,62.5
27,Jacob Markstrom,2020,31,CGY,43,43,22,19,2,111,...,23,8,0,0,0,2,8,3,5,62.5
28,Curtis McElhinney,2020,37,TBL,12,12,4,6,2,37,...,5,4,0,0,0,2,11,5,6,54.5
29,Elvis Merzlikins,2020,26,CBJ,28,23,8,12,5,69,...,14,2,0,1,1,0,10,1,9,90.0
30,Ryan Miller,2020,40,ANA,16,14,4,8,2,51,...,5,4,0,0,0,0,6,3,3,50.0
31,Petr Mrazek,2020,28,CAR,12,12,6,2,3,23,...,7,1,0,0,0,0,7,2,5,71.4
32,Matt Murray,2020,26,OTT,27,25,10,13,1,79,...,14,8,0,1,1,2,6,1,5,83.3
33,Alex Nedeljkovic,2020,25,CAR,23,23,15,5,3,44,...,15,0,0,1,1,2,3,0,3,100.0
34,Jake Oettinger,2020,22,DAL,29,24,11,8,7,63,...,12,3,0,1,1,4,10,5,5,50.0
35,Calvin Petersen,2020,26,LAK,35,32,9,18,5,97,...,16,3,0,1,1,0,2,1,1,50.0
36,Carey Price,2020,33,MTL,25,25,12,7,5,65,...,14,6,0,0,0,0,16,6,10,62.5
37,Jonathan Quick,2020,35,LAK,22,22,11,9,2,58,...,10,4,0,0,0,0,4,2,2,50.0
38,Tuukka Rask,2020,33,BOS,24,24,15,5,2,53,...,16,5,0,2,2,0,8,1,7,87.5
39,James Reimer,2020,32,CAR,22,21,15,5,2,59,...,10,1,0,0,0,0,15,5,10,66.7
40,Pekka Rinne,2020,38,NSH,24,21,10,12,1,62,...,12,3,0,1,1,0,8,2,6,75.0
41,Ilya Samsonov,2020,23,WSH,19,18,13,4,1,49,...,7,3,0,1,1,0,7,2,5,71.4
42,Juuse Saros,2020,25,NSH,36,35,21,11,1,78,...,22,5,0,0,0,2,8,0,8,100.0
43,Igor Shesterkin,2020,25,NYR,35,31,16,14,3,83,...,20,2,0,0,0,0,6,3,3,50.0
44,Ilya Sorokin,2020,25,NYI,22,21,13,6,3,46,...,15,3,0,0,0,0,16,2,14,87.5
45,Anthony Stolarz,2020,27,ANA,8,7,4,3,0,17,...,5,1,0,1,1,0,3,0,3,100.0
46,Malcolm Subban,2020,27,CHI,16,14,6,8,1,47,...,6,4,0,0,0,0,3,0,3,100.0
47,Jeremy Swayman,2020,22,BOS,10,10,7,3,0,15,...,9,0,0,0,0,0,2,0,2,100.0
48,Cam Talbot,2020,33,MIN,33,33,19,8,5,86,...,21,2,0,0,0,0,11,3,8,72.7
49,Dustin Tokarski,2020,31,BUF,13,10,2,8,2,43,...,5,1,0,1,1,0,2,2,0,0.0
50,Linus Ullmark,2020,27,BUF,20,20,9,6,3,49,...,11,0,0,0,0,0,13,1,12,92.3
51,Vitek Vanecek,2020,25,WSH,37,36,21,10,4,95,...,18,6,0,0,0,0,9,1,8,88.9
52,Semyon Varlamov,2020,32,NYI,36,35,19,11,4,72,...,26,4,0,1,1,2,8,4,4,50.0
53,Andrei Vasilevskiy,2020,26,TBL,42,42,31,10,1,93,...,24,0,0,4,4,0,3,1,2,66.7
54,Scott Wedgewood,2020,28,NJD,16,15,3,8,3,46,...,5,4,0,0,0,0,7,3,4,57.1

In [82]:
missing = pd.concat([goalies_2021.isnull().sum(), 100 * goalies_2021.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

            Count    %
Player          0  0.0
SUT             0  0.0
SOT_Saved       0  0.0
SOT_Scored      0  0.0
SOT_Att         0  0.0
PIM             0  0.0
PTS             0  0.0
A               0  0.0
G               0  0.0
RBS             0  0.0
QS              0  0.0
MIN             0  0.0
GPS             0  0.0
GAA             0  0.0
Season          0  0.0
SV_Pct          0  0.0
SV              0  0.0
SA              0  0.0
GA              0  0.0
TplusOTL        0  0.0
L               0  0.0
W               0  0.0
GS              0  0.0
GP              0  0.0
Tm              0  0.0
Age             0  0.0
SOT_Pct         0  0.0

In [83]:

goalies_2021.to_csv('./Clean/goalies2020.csv')