In [1]:
import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
import os
import seaborn as sns
from datetime import datetime
import fnmatch
import sys
import glob

#from library.sb_utils import save_file

Bad key text.latex.unicode in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 112 ('text.latex.unicode : False # use "ucs" and "inputenc" LaTeX packages for handling')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key savefig.frameon in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 423 ('savefig.frameon : True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key nbagg.transparent in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 426 ('nbagg.transparent: True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key pgf.debug in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 446 ('pgf.debug           : False')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.level in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 477 ('verbose.level  : silent      # one of silent, helpful, debug, debug-annoying')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.fileo in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 478 ('verbose.fileo  : sys.stdout  # a log filename, sys.stdout or sys.stderr')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key animation.mencoder_path in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 509 ('animation.mencoder_path: mencoder')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key animation.mencoder_args in file c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 512 ('animation.mencoder_args:          # Additional arguments to pass to mencoder')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In c:\users\squatch\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

In [172]:
contracts= pd.read_excel('Contracts/contracts.xlsx', engine='openpyxl')

In [108]:
######
order in order of date (descending ) and indexed on player name (??) so everything in the 
line stays together


also probably make a 'for loop' to loop through stats folders and make one large stat file


how should i handle contract extensions????

SyntaxError: invalid syntax (<ipython-input-108-da41f35f3407>, line 2)

In [209]:
contracts

,PLAYER,AGE,POS,TEAM,DATE,TYPE,EXTENSION,STRUCTURE,LENGTH,VALUE,CAP HIT
49,Fedor Tyutin,23,LD,NYR,2006-08-02,Standard,NaN,1-way,2,1975000,987500
48,Daniel Briere,28,C,BUF,2006-08-03,Standard,NaN,1-way,1,5000000,5000000
47,Brad Boyes,24,"RW, C",BOS,2006-08-04,Standard,NaN,1-way,2,3000000,1500000
46,Marc-André Fleury,21,G,PIT,2006-08-05,Standard,NaN,1-way,2,2598500,1294750
45,Milan Jurcina,23,D,BOS,2006-08-07,Standard,NaN,1-way,1,500000,500000
...,...,...,...,...,...,...,...,...,...,...,...
754,Joe Snively,25,LW,WSH,2021-06-03,Standard,✔,2-way,1,750000,750000
752,Samuel Ersson,21,G,PHI,2021-06-03,Entry-Level,NaN,2-way,3,2775000,859167
751,Nils Lundkvist,20,RD,NYR,2021-06-03,Entry-Level,NaN,2-way,3,5325000,925000
750,Mattias Norlinder,21,LD,MTL,2021-06-03,Entry-Level,NaN,2-way,3,2775000,859167
753,Andreas Wingerli,23,C,COL,2021-06-03,Entry-Level,NaN,2-way,1,925000,842500

In [210]:
contracts= contracts.sort_values('DATE', ascending=True)

In [211]:
contracts

,PLAYER,AGE,POS,TEAM,DATE,TYPE,EXTENSION,STRUCTURE,LENGTH,VALUE,CAP HIT
49,Fedor Tyutin,23,LD,NYR,2006-08-02,Standard,NaN,1-way,2,1975000,987500
48,Daniel Briere,28,C,BUF,2006-08-03,Standard,NaN,1-way,1,5000000,5000000
47,Brad Boyes,24,"RW, C",BOS,2006-08-04,Standard,NaN,1-way,2,3000000,1500000
46,Marc-André Fleury,21,G,PIT,2006-08-05,Standard,NaN,1-way,2,2598500,1294750
45,Milan Jurcina,23,D,BOS,2006-08-07,Standard,NaN,1-way,1,500000,500000
...,...,...,...,...,...,...,...,...,...,...,...
751,Nils Lundkvist,20,RD,NYR,2021-06-03,Entry-Level,NaN,2-way,3,5325000,925000
750,Mattias Norlinder,21,LD,MTL,2021-06-03,Entry-Level,NaN,2-way,3,2775000,859167
754,Joe Snively,25,LW,WSH,2021-06-03,Standard,✔,2-way,1,750000,750000
752,Samuel Ersson,21,G,PHI,2021-06-03,Entry-Level,NaN,2-way,3,2775000,859167
753,Andreas Wingerli,23,C,COL,2021-06-03,Entry-Level,NaN,2-way,1,925000,842500

In [212]:
contracts.columns

Index(['PLAYER', 'AGE', 'POS', 'TEAM', 'DATE', 'TYPE', 'EXTENSION',
       'STRUCTURE', 'LENGTH', 'VALUE', 'CAP HIT'],
      dtype='object')

In [213]:
contracts =contracts.drop(columns='Unnamed: 1')

KeyError: "['Unnamed: 1'] not found in axis"

In [214]:
contracts.head()

,PLAYER,AGE,POS,TEAM,DATE,TYPE,EXTENSION,STRUCTURE,LENGTH,VALUE,CAP HIT
49,Fedor Tyutin,23,LD,NYR,2006-08-02,Standard,NaN,1-way,2,1975000,987500
48,Daniel Briere,28,C,BUF,2006-08-03,Standard,NaN,1-way,1,5000000,5000000
47,Brad Boyes,24,"RW, C",BOS,2006-08-04,Standard,NaN,1-way,2,3000000,1500000
46,Marc-André Fleury,21,G,PIT,2006-08-05,Standard,NaN,1-way,2,2598500,1294750
45,Milan Jurcina,23,D,BOS,2006-08-07,Standard,NaN,1-way,1,500000,500000

In [215]:
non_ext= contracts[contracts['EXTENSION'].isnull()]

In [216]:
non_ext.head(40)

,PLAYER,AGE,POS,TEAM,DATE,TYPE,EXTENSION,STRUCTURE,LENGTH,VALUE,CAP HIT
49,Fedor Tyutin,23,LD,NYR,2006-08-02,Standard,NaN,1-way,2,1975000,987500
48,Daniel Briere,28,C,BUF,2006-08-03,Standard,NaN,1-way,1,5000000,5000000
47,Brad Boyes,24,"RW, C",BOS,2006-08-04,Standard,NaN,1-way,2,3000000,1500000
46,Marc-André Fleury,21,G,PIT,2006-08-05,Standard,NaN,1-way,2,2598500,1294750
45,Milan Jurcina,23,D,BOS,2006-08-07,Standard,NaN,1-way,1,500000,500000
44,Michael Sauer,19,D,NYR,2006-08-08,Entry-Level,NaN,2-way,3,1770000,590000
43,Christian Backman,26,LD,STL,2006-08-09,Standard,NaN,1-way,3,6900000,2300000
41,Nate Guenin,23,RD,PHI,2006-08-16,Entry-Level,NaN,2-way,2,1700000,585000
40,Phil Kessel,18,RW,BOS,2006-08-17,Entry-Level,NaN,2-way,3,6600000,850000
39,Kevin Bieksa,25,RD,VAN,2006-08-17,Standard,NaN,1-way,2,1050000,525000
38,Patrice Bergeron,21,C,BOS,2006-08-22,Standard,NaN,1-way,5,23750000,4750000
37,Johan Franzen,26,"RW, LW",DET,2006-08-25,Standard,NaN,1-way,3,2825000,941667
36,Jean-Pierre Dumont,28,RW,NSH,2006-08-29,Standard,NaN,1-way,2,4500000,2250000
35,Trevor Daley,22,RD,DAL,2006-08-31,Standard,NaN,1-way,2,1575000,787500
34,Ilya Bryzgalov,26,G,ANA,2006-09-06,Standard,NaN,1-way,2,2362500,1181250
33,Kari Lehtonen,22,G,ATL,2006-09-07,Standard,NaN,1-way,2,3700000,1850000
32,Ryan Miller,26,G,BUF,2006-09-08,Standard,NaN,1-way,3,8000000,2666667
30,Simon Gagne,26,RW,PHI,2006-09-11,Standard,NaN,1-way,5,26250000,5250000
28,Joffrey Lupul,22,"LW, RW",EDM,2006-09-12,Standard,NaN,1-way,3,6935000,2311667
27,Rick DiPietro,24,G,NYI,2006-09-12,Standard,NaN,1-way,15,67500000,4500000
26,Matt Stajan,22,C,TOR,2006-09-13,Standard,NaN,1-way,2,1750000,875000
25,Ryan Kesler,21,"C, RW",VAN,2006-09-14,Standard,NaN,1-way,1,1900000,1900000
24,Tim Gleason,23,D,LAK,2006-09-17,Standard,NaN,1-way,2,2350000,1175000
23,Dustin Brown,21,"RW, LW",LAK,2006-09-17,Standard,NaN,1-way,2,2350000,1175000
20,Derick Brassard,18,"LW, C",CBJ,2006-09-21,Entry-Level,NaN,2-way,3,3740000,821667
21,Dan Hamhuis,23,LD,NSH,2006-09-21,Standard,NaN,1-way,4,8000000,2000000
19,Oskars Bartulis,20,D,PHI,2006-09-23,Entry-Level,NaN,2-way,3,1550000,516666
18,Darren Helm,19,"C, LW, RW",DET,2006-09-27,Entry-Level,NaN,2-way,3,1798332,597833
16,Michael Grabner,18,"LW, RW",VAN,2006-09-28,Entry-Level,NaN,2-way,3,2700000,850000
15,Nikolai Zherdev,21,LW,CBJ,2006-09-28,Standard,NaN,1-way,3,7500000,2500000
14,Guillaume Latendresse,19,LW,MTL,2006-09-29,Entry-Level,NaN,2-way,3,2550000,850000
11,Jordan Staal,17,"C, LW",PIT,2006-10-02,Entry-Level,NaN,2-way,3,6600000,850000
12,Kris Letang,19,RD,PIT,2006-10-02,Entry-Level,NaN,2-way,3,2505000,638333
10,Brian Gionta,27,RW,NJD,2006-10-03,Standard,NaN,1-way,3,12000000,4000000
9,Paul Martin,25,LD,NJD,2006-10-03,Standard,NaN,1-way,1,2000000,2000000
7,Jonathan Bernier,18,G,LAK,2006-10-13,Entry-Level,NaN,2-way,3,2700000,850000
6,Tuomo Ruutu,23,"LW, RW",CHI,2006-10-13,Standard,NaN,1-way,2,3750000,1875000
5,James Neal,19,"RW, LW",DAL,2006-10-20,Entry-Level,NaN,2-way,3,2465000,646667
4,Cal O'Reilly,20,C,NSH,2006-11-06,Entry-Level,NaN,2-way,3,1600000,500000
2,Brendan Mikkelson,19,D,ANA,2006-11-30,Entry-Level,NaN,2-way,3,1845000,615000

In [217]:
non_ext= non_ext.drop(columns='EXTENSION')
non_ext

,PLAYER,AGE,POS,TEAM,DATE,TYPE,STRUCTURE,LENGTH,VALUE,CAP HIT
49,Fedor Tyutin,23,LD,NYR,2006-08-02,Standard,1-way,2,1975000,987500
48,Daniel Briere,28,C,BUF,2006-08-03,Standard,1-way,1,5000000,5000000
47,Brad Boyes,24,"RW, C",BOS,2006-08-04,Standard,1-way,2,3000000,1500000
46,Marc-André Fleury,21,G,PIT,2006-08-05,Standard,1-way,2,2598500,1294750
45,Milan Jurcina,23,D,BOS,2006-08-07,Standard,1-way,1,500000,500000
...,...,...,...,...,...,...,...,...,...,...
756,Keean Washkurak,19,C,STL,2021-06-01,Entry-Level,2-way,3,2625000,862500
751,Nils Lundkvist,20,RD,NYR,2021-06-03,Entry-Level,2-way,3,5325000,925000
750,Mattias Norlinder,21,LD,MTL,2021-06-03,Entry-Level,2-way,3,2775000,859167
752,Samuel Ersson,21,G,PHI,2021-06-03,Entry-Level,2-way,3,2775000,859167
753,Andreas Wingerli,23,C,COL,2021-06-03,Entry-Level,2-way,1,925000,842500

In [219]:
non_ext= non_ext.rename(columns={'PLAYER':'Player'})
non_ext

,Player,AGE,POS,TEAM,DATE,TYPE,STRUCTURE,LENGTH,VALUE,CAP HIT
49,Fedor Tyutin,23,LD,NYR,2006-08-02,Standard,1-way,2,1975000,987500
48,Daniel Briere,28,C,BUF,2006-08-03,Standard,1-way,1,5000000,5000000
47,Brad Boyes,24,"RW, C",BOS,2006-08-04,Standard,1-way,2,3000000,1500000
46,Marc-André Fleury,21,G,PIT,2006-08-05,Standard,1-way,2,2598500,1294750
45,Milan Jurcina,23,D,BOS,2006-08-07,Standard,1-way,1,500000,500000
...,...,...,...,...,...,...,...,...,...,...
756,Keean Washkurak,19,C,STL,2021-06-01,Entry-Level,2-way,3,2625000,862500
751,Nils Lundkvist,20,RD,NYR,2021-06-03,Entry-Level,2-way,3,5325000,925000
750,Mattias Norlinder,21,LD,MTL,2021-06-03,Entry-Level,2-way,3,2775000,859167
752,Samuel Ersson,21,G,PHI,2021-06-03,Entry-Level,2-way,3,2775000,859167
753,Andreas Wingerli,23,C,COL,2021-06-03,Entry-Level,2-way,1,925000,842500

In [220]:
non_etl= non_ext[non_ext['TYPE']!='Entry-Level']

In [221]:
non_etl.head(40)

,Player,AGE,POS,TEAM,DATE,TYPE,STRUCTURE,LENGTH,VALUE,CAP HIT
49,Fedor Tyutin,23,LD,NYR,2006-08-02,Standard,1-way,2,1975000,987500
48,Daniel Briere,28,C,BUF,2006-08-03,Standard,1-way,1,5000000,5000000
47,Brad Boyes,24,"RW, C",BOS,2006-08-04,Standard,1-way,2,3000000,1500000
46,Marc-André Fleury,21,G,PIT,2006-08-05,Standard,1-way,2,2598500,1294750
45,Milan Jurcina,23,D,BOS,2006-08-07,Standard,1-way,1,500000,500000
43,Christian Backman,26,LD,STL,2006-08-09,Standard,1-way,3,6900000,2300000
39,Kevin Bieksa,25,RD,VAN,2006-08-17,Standard,1-way,2,1050000,525000
38,Patrice Bergeron,21,C,BOS,2006-08-22,Standard,1-way,5,23750000,4750000
37,Johan Franzen,26,"RW, LW",DET,2006-08-25,Standard,1-way,3,2825000,941667
36,Jean-Pierre Dumont,28,RW,NSH,2006-08-29,Standard,1-way,2,4500000,2250000
35,Trevor Daley,22,RD,DAL,2006-08-31,Standard,1-way,2,1575000,787500
34,Ilya Bryzgalov,26,G,ANA,2006-09-06,Standard,1-way,2,2362500,1181250
33,Kari Lehtonen,22,G,ATL,2006-09-07,Standard,1-way,2,3700000,1850000
32,Ryan Miller,26,G,BUF,2006-09-08,Standard,1-way,3,8000000,2666667
30,Simon Gagne,26,RW,PHI,2006-09-11,Standard,1-way,5,26250000,5250000
28,Joffrey Lupul,22,"LW, RW",EDM,2006-09-12,Standard,1-way,3,6935000,2311667
27,Rick DiPietro,24,G,NYI,2006-09-12,Standard,1-way,15,67500000,4500000
26,Matt Stajan,22,C,TOR,2006-09-13,Standard,1-way,2,1750000,875000
25,Ryan Kesler,21,"C, RW",VAN,2006-09-14,Standard,1-way,1,1900000,1900000
24,Tim Gleason,23,D,LAK,2006-09-17,Standard,1-way,2,2350000,1175000
23,Dustin Brown,21,"RW, LW",LAK,2006-09-17,Standard,1-way,2,2350000,1175000
21,Dan Hamhuis,23,LD,NSH,2006-09-21,Standard,1-way,4,8000000,2000000
15,Nikolai Zherdev,21,LW,CBJ,2006-09-28,Standard,1-way,3,7500000,2500000
10,Brian Gionta,27,RW,NJD,2006-10-03,Standard,1-way,3,12000000,4000000
9,Paul Martin,25,LD,NJD,2006-10-03,Standard,1-way,1,2000000,2000000
6,Tuomo Ruutu,23,"LW, RW",CHI,2006-10-13,Standard,1-way,2,3750000,1875000
99,Ryan Craig,25,C,TBL,2007-08-06,Standard,1-way,1,850000,850000
98,Mike Cammalleri,25,"LW, C",LAK,2007-08-07,Standard,1-way,2,6700000,3350000
96,Mike Weaver,29,D,PIT,2007-08-08,Standard,2-way,1,600000,600000
94,Andy Sutton,32,D,NYI,2007-08-10,Standard,1-way,3,9000000,3000000
93,James Wisniewski,23,RD,CHI,2007-08-10,Standard,1-way,1,650000,650000
91,Pierre-Alexandre Parenteau,24,RW,CHI,2007-08-13,Standard,2-way,1,550000,550000
89,Paul Martin,26,LD,NJD,2007-08-16,Standard,1-way,3,11500000,3833333
86,Stephen Weiss,24,C,FLA,2007-08-23,Standard,1-way,6,18600000,3100000
83,John Erskine,27,D,WSH,2007-08-27,Standard,1-way,2,1075000,537500
82,Keith Ballard,24,D,ARI,2007-08-29,Standard,1-way,2,4550000,2275000
81,Jussi Jokinen,24,"LW, RW",DAL,2007-08-30,Standard,1-way,2,3625000,1812500
78,Noah Welch,25,LD,FLA,2007-09-12,Standard,1-way,2,1300000,650000
74,Adam Hall,27,RW,PIT,2007-10-01,Standard,2-way,1,525000,525000
69,David Tanabe,26,D,CAR,2007-10-06,Standard,1-way,2,1500000,750000

In [228]:
clean_contracts= non_etl.set_index('Player')
clean_contracts

,AGE,POS,TEAM,DATE,TYPE,STRUCTURE,LENGTH,VALUE,CAP HIT
Player,,,,,,,,,
Fedor Tyutin,23,LD,NYR,2006-08-02,Standard,1-way,2,1975000,987500
Daniel Briere,28,C,BUF,2006-08-03,Standard,1-way,1,5000000,5000000
Brad Boyes,24,"RW, C",BOS,2006-08-04,Standard,1-way,2,3000000,1500000
Marc-André Fleury,21,G,PIT,2006-08-05,Standard,1-way,2,2598500,1294750
Milan Jurcina,23,D,BOS,2006-08-07,Standard,1-way,1,500000,500000
...,...,...,...,...,...,...,...,...,...
Cavan Fitzgerald,24,LD,CAR,2021-05-11,Standard,2-way,2,1500000,750000
Henrik Borgström,23,C,CHI,2021-05-12,Standard,1-way,2,2000000,1000000
Erik Källgren,24,G,TOR,2021-05-19,Standard,2-way,2,1500000,750000
Clark Bishop,25,C,OTT,2021-05-20,Standard,2-way,1,800000,800000
Jeff Malott,24,LW,WPG,2021-05-31,Standard,2-way,1,780000,780000

In [229]:
clean_contracts.head(40)

,AGE,POS,TEAM,DATE,TYPE,STRUCTURE,LENGTH,VALUE,CAP HIT
Player,,,,,,,,,
Fedor Tyutin,23,LD,NYR,2006-08-02,Standard,1-way,2,1975000,987500
Daniel Briere,28,C,BUF,2006-08-03,Standard,1-way,1,5000000,5000000
Brad Boyes,24,"RW, C",BOS,2006-08-04,Standard,1-way,2,3000000,1500000
Marc-André Fleury,21,G,PIT,2006-08-05,Standard,1-way,2,2598500,1294750
Milan Jurcina,23,D,BOS,2006-08-07,Standard,1-way,1,500000,500000
Christian Backman,26,LD,STL,2006-08-09,Standard,1-way,3,6900000,2300000
Kevin Bieksa,25,RD,VAN,2006-08-17,Standard,1-way,2,1050000,525000
Patrice Bergeron,21,C,BOS,2006-08-22,Standard,1-way,5,23750000,4750000
Johan Franzen,26,"RW, LW",DET,2006-08-25,Standard,1-way,3,2825000,941667
Jean-Pierre Dumont,28,RW,NSH,2006-08-29,Standard,1-way,2,4500000,2250000
Trevor Daley,22,RD,DAL,2006-08-31,Standard,1-way,2,1575000,787500
Ilya Bryzgalov,26,G,ANA,2006-09-06,Standard,1-way,2,2362500,1181250
Kari Lehtonen,22,G,ATL,2006-09-07,Standard,1-way,2,3700000,1850000
Ryan Miller,26,G,BUF,2006-09-08,Standard,1-way,3,8000000,2666667
Simon Gagne,26,RW,PHI,2006-09-11,Standard,1-way,5,26250000,5250000
Joffrey Lupul,22,"LW, RW",EDM,2006-09-12,Standard,1-way,3,6935000,2311667
Rick DiPietro,24,G,NYI,2006-09-12,Standard,1-way,15,67500000,4500000
Matt Stajan,22,C,TOR,2006-09-13,Standard,1-way,2,1750000,875000
Ryan Kesler,21,"C, RW",VAN,2006-09-14,Standard,1-way,1,1900000,1900000
Tim Gleason,23,D,LAK,2006-09-17,Standard,1-way,2,2350000,1175000
Dustin Brown,21,"RW, LW",LAK,2006-09-17,Standard,1-way,2,2350000,1175000
Dan Hamhuis,23,LD,NSH,2006-09-21,Standard,1-way,4,8000000,2000000
Nikolai Zherdev,21,LW,CBJ,2006-09-28,Standard,1-way,3,7500000,2500000
Brian Gionta,27,RW,NJD,2006-10-03,Standard,1-way,3,12000000,4000000
Paul Martin,25,LD,NJD,2006-10-03,Standard,1-way,1,2000000,2000000
Tuomo Ruutu,23,"LW, RW",CHI,2006-10-13,Standard,1-way,2,3750000,1875000
Ryan Craig,25,C,TBL,2007-08-06,Standard,1-way,1,850000,850000
Mike Cammalleri,25,"LW, C",LAK,2007-08-07,Standard,1-way,2,6700000,3350000
Mike Weaver,29,D,PIT,2007-08-08,Standard,2-way,1,600000,600000
Andy Sutton,32,D,NYI,2007-08-10,Standard,1-way,3,9000000,3000000
James Wisniewski,23,RD,CHI,2007-08-10,Standard,1-way,1,650000,650000
Pierre-Alexandre Parenteau,24,RW,CHI,2007-08-13,Standard,2-way,1,550000,550000
Paul Martin,26,LD,NJD,2007-08-16,Standard,1-way,3,11500000,3833333
Stephen Weiss,24,C,FLA,2007-08-23,Standard,1-way,6,18600000,3100000
John Erskine,27,D,WSH,2007-08-27,Standard,1-way,2,1075000,537500
Keith Ballard,24,D,ARI,2007-08-29,Standard,1-way,2,4550000,2275000
Jussi Jokinen,24,"LW, RW",DAL,2007-08-30,Standard,1-way,2,3625000,1812500
Noah Welch,25,LD,FLA,2007-09-12,Standard,1-way,2,1300000,650000
Adam Hall,27,RW,PIT,2007-10-01,Standard,2-way,1,525000,525000
David Tanabe,26,D,CAR,2007-10-06,Standard,1-way,2,1500000,750000

In [230]:
### SAVE CLEAN CONTRACTS
clean_contracts.to_csv('clean_contracts.csv')

In [ ]:
#####STATS CONSOLIDATION

In [141]:
cwd_2= os.path.abspath('Stats')
stat_folders= os.listdir(cwd_2)

In [169]:
cwd_2

'C:\\Users\\Squatch\\Desktop\\Springboard Course\\Assignments\\Springboard\\Capstone 2\\Stats'

In [189]:
stat_folders

['1999-2000',
 '2000-01',
 '2001-02',
 '2002-03',
 '2003-04',
 '2005-06',
 '2006-07',
 '2007-08',
 '2008-09',
 '2009-10',
 '2010-11',
 '2011-12',
 '2012-13',
 '2013-14',
 '2014-15',
 '2015-16',
 '2016-17',
 '2017-18',
 '2018-19',
 '2019-20',
 '2020-21']

In [197]:
C:\Users\Squatch\Desktop\Springboard Course\Assignments\Springboard\Capstone 2\Stats

SyntaxError: unexpected character after line continuation character (<ipython-input-197-3ff683702dbc>, line 1)

In [2]:
path = r'C:\Users\Squatch\Desktop\Springboard Course\Assignments\Springboard\Capstone 2\Stats'
files = os.listdir(path)
files

['2007-08',
 '2008-09',
 '2009-10',
 '2010-11',
 '2011-12',
 '2012-13',
 '2013-14',
 '2014-15',
 '2015-16',
 '2016-17',
 '2017-18',
 '2018-19',
 '2019-20',
 '2020-21']

In [3]:
xl_list = glob.glob('./Stats\**\*.xlsx', 
                   recursive = True)
for file in xl_list:
    print(file)

./Stats\2007-08\2007-08goalies.xlsx
./Stats\2007-08\2007-08skaters.xlsx
./Stats\2007-08\2007-08skaters_adv.xlsx
./Stats\2008-09\2008-09goalies.xlsx
./Stats\2008-09\2008-09goalies_shootout.xlsx
./Stats\2008-09\2008-09skaters.xlsx
./Stats\2008-09\2008-09skaters_adv.xlsx
./Stats\2008-09\2008-09skaters_shootout.xlsx
./Stats\2009-10\2009-10goalies.xlsx
./Stats\2009-10\2009-10goalies_shootout.xlsx
./Stats\2009-10\2009-10skaters.xlsx
./Stats\2009-10\2009-10skaters_adv.xlsx
./Stats\2009-10\2009-10skaters_shootout.xlsx
./Stats\2010-11\2010-11goalies.xlsx
./Stats\2010-11\2010-11goalies_shootout.xlsx
./Stats\2010-11\2010-11skaters.xlsx
./Stats\2010-11\2010-11skaters_adv.xlsx
./Stats\2010-11\2010-11skaters_shootout.xlsx
./Stats\2011-12\2011-12goalies.xlsx
./Stats\2011-12\2011-12goalies_shootout.xlsx
./Stats\2011-12\2011-12skaters.xlsx
./Stats\2011-12\2011-12skaters_adv.xlsx
./Stats\2011-12\2011-12skaters_shootout.xlsx
./Stats\2012-13\2012-13goalies.xlsx
./Stats\2012-13\2012-13goalies_shootout.xlsx
./Stats\2012-13\2012-13skaters.xlsx
./Stats\2012-13\2012-13skaters_adv.xlsx
./Stats\2012-13\2012-13skaters_shootout.xlsx
./Stats\2013-14\2013-14goalies.xlsx
./Stats\2013-14\2013-14goalies_shootout.xlsx
./Stats\2013-14\2013-14skaters.xlsx
./Stats\2013-14\2013-14skaters_adv.xlsx
./Stats\2013-14\2013-14skaters_shootout.xlsx
./Stats\2014-15\2014-15goalies.xlsx
./Stats\2014-15\2014-15goalies_shootout.xlsx
./Stats\2014-15\2014-15skaters.xlsx
./Stats\2014-15\2014-15skaters_adv.xlsx
./Stats\2014-15\2014-15skaters_misc.xlsx
./Stats\2015-16\2015-16goalies.xlsx
./Stats\2015-16\2015-16goalies_shootout.xlsx
./Stats\2015-16\2015-16skaters.xlsx
./Stats\2015-16\2015-16skaters_adv.xlsx
./Stats\2015-16\2015-16skaters_misc.xlsx
./Stats\2016-17\2016-17goalies.xlsx
./Stats\2016-17\2016-17goalies_shootout.xlsx
./Stats\2016-17\2016-17skaters.xlsx
./Stats\2016-17\2016-17skaters_adv.xlsx
./Stats\2016-17\2016-17skaters_misc.xlsx
./Stats\2017-18\2017-18goalie.xlsx
./Stats\2017-18\2017-18goalie_shootout.xlsx
./Stats\2017-18\2017-18skaters.xlsx
./Stats\2017-18\2017-18skaters_adv.xlsx
./Stats\2017-18\2017-18skater_misc.xlsx
./Stats\2018-19\2018-19goalie.xlsx
./Stats\2018-19\2018-19goalie_shootout.xlsx
./Stats\2018-19\2018-19skaters.xlsx
./Stats\2018-19\2018-19skaters_adv.xlsx
./Stats\2018-19\2018-19skaters_misc.xlsx
./Stats\2019-20\2019-20goalies.xlsx
./Stats\2019-20\2019-20goalie_shootout.xlsx
./Stats\2019-20\2019-20skater.xlsx
./Stats\2019-20\2019-20skater_adv.xlsx
./Stats\2019-20\2019-20skater_misc.xlsx
./Stats\2020-21\2020-21goalies.xlsx
./Stats\2020-21\2020-21goalie_shootout.xlsx
./Stats\2020-21\2020-21skaters.xlsx
./Stats\2020-21\2020-21skater_adv.xlsx
./Stats\2020-21\2020-21skater_misc.xlsx

In [4]:
files_xlsx= [f for f in xl_list if f[-4:] == "xlsx"]
files_xlsx

['./Stats\\2007-08\\2007-08goalies.xlsx',
 './Stats\\2007-08\\2007-08skaters.xlsx',
 './Stats\\2007-08\\2007-08skaters_adv.xlsx',
 './Stats\\2008-09\\2008-09goalies.xlsx',
 './Stats\\2008-09\\2008-09goalies_shootout.xlsx',
 './Stats\\2008-09\\2008-09skaters.xlsx',
 './Stats\\2008-09\\2008-09skaters_adv.xlsx',
 './Stats\\2008-09\\2008-09skaters_shootout.xlsx',
 './Stats\\2009-10\\2009-10goalies.xlsx',
 './Stats\\2009-10\\2009-10goalies_shootout.xlsx',
 './Stats\\2009-10\\2009-10skaters.xlsx',
 './Stats\\2009-10\\2009-10skaters_adv.xlsx',
 './Stats\\2009-10\\2009-10skaters_shootout.xlsx',
 './Stats\\2010-11\\2010-11goalies.xlsx',
 './Stats\\2010-11\\2010-11goalies_shootout.xlsx',
 './Stats\\2010-11\\2010-11skaters.xlsx',
 './Stats\\2010-11\\2010-11skaters_adv.xlsx',
 './Stats\\2010-11\\2010-11skaters_shootout.xlsx',
 './Stats\\2011-12\\2011-12goalies.xlsx',
 './Stats\\2011-12\\2011-12goalies_shootout.xlsx',
 './Stats\\2011-12\\2011-12skaters.xlsx',
 './Stats\\2011-12\\2011-12skaters_adv.xlsx',
 './Stats\\2011-12\\2011-12skaters_shootout.xlsx',
 './Stats\\2012-13\\2012-13goalies.xlsx',
 './Stats\\2012-13\\2012-13goalies_shootout.xlsx',
 './Stats\\2012-13\\2012-13skaters.xlsx',
 './Stats\\2012-13\\2012-13skaters_adv.xlsx',
 './Stats\\2012-13\\2012-13skaters_shootout.xlsx',
 './Stats\\2013-14\\2013-14goalies.xlsx',
 './Stats\\2013-14\\2013-14goalies_shootout.xlsx',
 './Stats\\2013-14\\2013-14skaters.xlsx',
 './Stats\\2013-14\\2013-14skaters_adv.xlsx',
 './Stats\\2013-14\\2013-14skaters_shootout.xlsx',
 './Stats\\2014-15\\2014-15goalies.xlsx',
 './Stats\\2014-15\\2014-15goalies_shootout.xlsx',
 './Stats\\2014-15\\2014-15skaters.xlsx',
 './Stats\\2014-15\\2014-15skaters_adv.xlsx',
 './Stats\\2014-15\\2014-15skaters_misc.xlsx',
 './Stats\\2015-16\\2015-16goalies.xlsx',
 './Stats\\2015-16\\2015-16goalies_shootout.xlsx',
 './Stats\\2015-16\\2015-16skaters.xlsx',
 './Stats\\2015-16\\2015-16skaters_adv.xlsx',
 './Stats\\2015-16\\2015-16skaters_misc.xlsx',
 './Stats\\2016-17\\2016-17goalies.xlsx',
 './Stats\\2016-17\\2016-17goalies_shootout.xlsx',
 './Stats\\2016-17\\2016-17skaters.xlsx',
 './Stats\\2016-17\\2016-17skaters_adv.xlsx',
 './Stats\\2016-17\\2016-17skaters_misc.xlsx',
 './Stats\\2017-18\\2017-18goalie.xlsx',
 './Stats\\2017-18\\2017-18goalie_shootout.xlsx',
 './Stats\\2017-18\\2017-18skaters.xlsx',
 './Stats\\2017-18\\2017-18skaters_adv.xlsx',
 './Stats\\2017-18\\2017-18skater_misc.xlsx',
 './Stats\\2018-19\\2018-19goalie.xlsx',
 './Stats\\2018-19\\2018-19goalie_shootout.xlsx',
 './Stats\\2018-19\\2018-19skaters.xlsx',
 './Stats\\2018-19\\2018-19skaters_adv.xlsx',
 './Stats\\2018-19\\2018-19skaters_misc.xlsx',
 './Stats\\2019-20\\2019-20goalies.xlsx',
 './Stats\\2019-20\\2019-20goalie_shootout.xlsx',
 './Stats\\2019-20\\2019-20skater.xlsx',
 './Stats\\2019-20\\2019-20skater_adv.xlsx',
 './Stats\\2019-20\\2019-20skater_misc.xlsx',
 './Stats\\2020-21\\2020-21goalies.xlsx',
 './Stats\\2020-21\\2020-21goalie_shootout.xlsx',
 './Stats\\2020-21\\2020-21skaters.xlsx',
 './Stats\\2020-21\\2020-21skater_adv.xlsx',
 './Stats\\2020-21\\2020-21skater_misc.xlsx']

In [20]:
#df= pd.DataFrame()

In [21]:
for xl in files_xlsx:
    data= pd.read_excel(xl, engine= 'openpyxl')
    df= df.append(data)

KeyboardInterrupt:

In [215]:
#df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Goalie Stats,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Tm,Per Game,Adjusted,Plus/Minus,Possession Quality,Point Shares,Shootouts,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,Rk,Player,Age,Tm,GP,GS,W,L,T/O,GA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Jean-Sebastien Aubin,22,PIT,51,NaN,23,21,3,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Tom Barrasso,34,TOT,25,NaN,8,11,2,68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,Tom Barrasso,34,PIT,18,NaN,5,7,2,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,Tom Barrasso,34,OTT,7,NaN,3,4,0,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1070,1007,Zachary Jones,20,NYR,NaN,10,1,NaN,0.4,0.4,...,NaN,0,0,6,3.5,0.2,0,NaN,NaN,NaN
1071,1008,Zachary Senyshyn,23,BOS,NaN,8,0,NaN,0,0,...,NaN,0,0,0,1,-0.2,0,NaN,NaN,NaN
1072,1009,Zack Kassian,30,EDM,NaN,27,2,NaN,0.11,0.19,...,NaN,0.07,3,8,4.7,-0.2,0,NaN,NaN,NaN
1073,1010,Zack MacEwen,24,VAN,NaN,34,1,NaN,0.03,0.06,...,NaN,0.03,2,10,4,-0.5,0,NaN,NaN,NaN
1074,1011,Zdeno Chara,43,WSH,NaN,55,3,NaN,0.15,0.18,...,NaN,0.04,3,44,18.2,0,0,NaN,NaN,NaN

In [25]:
g0809=pd.DataFrame()
g0809= pd.read_excel('./Stats/2008-09/2008-09goalies.xlsx', engine= 'openpyxl')
g0809

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Goalie Stats,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Goalie Stats.2,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Scoring,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Rk,Player,Age,Tm,GP,GS,W,L,T/O,GA,...,MIN,QS,QS%,RBS,GA%-,GSAA,G,A,PTS,PIM
1,1,Craig Anderson,27,FLA,31,27,15,7,5,74,...,1636,16,0.593,6,83,15.4,0,1,1,2
2,2,Alex Auld,28,OTT,43,38,16,18,7,101,...,2449,22,0.579,4,97,3.41,0,0,0,2
3,3,Niklas Backstrom,30,MIN,71,71,37,24,8,159,...,4088,47,0.662,9,84,29.42,0,0,0,6
4,4,Martin Biron,31,PHI,55,53,29,19,5,146,...,3177,29,0.547,7,93,11.21,0,4,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,85,Steve Valiquette,31,NYR,15,12,5,5,2,39,...,823,7,0.583,1,101,-0.47,0,1,1,2
98,86,Semyon Varlamov,20,WSH,6,5,4,0,1,13,...,329,4,0.8,1,NaN,NaN,0,0,0,2
99,87,Tomas Vokoun,32,FLA,59,55,26,23,6,138,...,3324,33,0.6,4,81,31.75,0,1,1,2
100,88,Cam Ward,24,CAR,68,68,39,23,5,160,...,3928,43,0.632,10,92,13.96,0,1,1,4
101,89,Kevin Weekes,33,NJD,16,13,7,5,0,32,...,795,8,0.615,1,88,4.51,0,0,0,0

In [27]:
g0809t=g0809.T
g0809t

,0,1,2,3,4,5,6,7,8,9,...,92,93,94,95,96,97,98,99,100,101
Unnamed: 0,Rk,1,2,3,4,5,6,7,8,9,...,Rk,81,82,83,84,85,86,87,88,89
Unnamed: 1,Player,Craig Anderson,Alex Auld,Niklas Backstrom,Martin Biron,Ben Bishop,Brian Boucher,Martin Brodeur*,Ilya Bryzgalov,Peter Budaj,...,Player,Tim Thomas,Josh Tordjman,Vesa Toskala,Marty Turco,Steve Valiquette,Semyon Varlamov,Tomas Vokoun,Cam Ward,Kevin Weekes
Unnamed: 2,Age,27,28,30,31,22,32,36,28,26,...,Age,34,24,31,33,31,20,32,24,33
Unnamed: 3,Tm,FLA,OTT,MIN,PHI,STL,SJS,NJD,PHX,COL,...,Tm,BOS,PHX,TOR,DAL,NYR,WSH,FLA,CAR,NJD
Goalie Stats,GP,31,43,71,55,6,22,31,65,56,...,GP,54,2,53,74,15,6,59,68,16
Unnamed: 5,GS,27,38,71,53,3,20,30,62,55,...,GS,53,2,52,74,12,5,55,68,13
Unnamed: 6,W,15,16,37,29,1,12,19,26,20,...,W,36,0,22,33,5,4,26,39,7
Unnamed: 7,L,7,18,24,19,1,6,9,31,29,...,L,11,2,17,31,5,0,23,23,5
Unnamed: 8,T/O,5,7,8,5,1,3,3,6,5,...,T/O,7,0,11,10,2,1,6,5,0
Unnamed: 9,GA,74,101,159,146,12,47,73,187,154,...,GA,114,8,166,203,39,13,138,160,32
Unnamed: 10,SA,977,1141,2059,1718,112,563,870,1994,1531,...,SA,1694,62,1518,1993,421,159,1855,1901,399
Unnamed: 11,SV,903,1040,1900,1572,100,516,797,1807,1377,...,SV,1580,54,1352,1790,382,146,1717,1741,367
Unnamed: 12,SV%,0.924,0.911,0.923,0.915,0.893,0.917,0.916,0.906,0.899,...,SV%,0.933,0.871,0.891,0.898,0.907,0.918,0.926,0.916,0.92
Goalie Stats.1,GAA,2.71,2.47,2.33,2.76,2.94,2.18,2.42,2.98,2.86,...,GAA,2.1,4.08,3.26,2.81,2.84,2.37,2.49,2.44,2.42
Unnamed: 14,SO,3,1,8,2,0,2,5,3,2,...,SO,5,0,1,3,1,0,6,6,0
Unnamed: 15,GPS,7.6,7.2,15.6,11.5,0.5,3.9,5.9,11.4,7.6,...,GPS,14.7,0.1,6,9.6,2.5,1.1,14.6,12.9,2.9
Goalie Stats.2,MIN,1636,2449,4088,3177,245,1291,1814,3760,3232,...,MIN,3259,118,3056,4327,823,329,3324,3928,795
Unnamed: 17,QS,16,22,47,29,1,10,20,33,27,...,QS,39,0,23,38,7,4,33,43,8
Unnamed: 18,QS%,0.593,0.579,0.662,0.547,0.333,0.5,0.667,0.532,0.491,...,QS%,0.736,0,0.442,0.514,0.583,0.8,0.6,0.632,0.615
Unnamed: 19,RBS,6,4,9,7,0,1,5,13,14,...,RBS,3,0,13,22,1,1,4,10,1
Unnamed: 20,GA%-,83,97,84,93,NaN,91,92,102,110,...,GA%-,74,NaN,120,111,101,NaN,81,92,88
Unnamed: 21,GSAA,15.4,3.41,29.42,11.21,NaN,4.52,6.61,-4.53,-13.9,...,GSAA,41.02,NaN,-27.09,-20.62,-0.47,NaN,31.75,13.96,4.51
Scoring,G,0,0,0,0,0,0,0,0,0,...,G,0,0,0,0,0,0,0,0,0
Unnamed: 23,A,1,0,0,4,0,0,0,2,1,...,A,1,0,0,5,1,0,1,1,0
Unnamed: 24,PTS,1,0,0,4,0,0,0,2,1,...,PTS,1,0,0,5,1,0,1,1,0
Unnamed: 25,PIM,2,2,6,0,0,2,4,4,0,...,PIM,6,0,2,18,2,2,2,4,0

In [28]:
g0809t_new=g0809t.set_index(0)
g0809t_new

,1,2,3,4,5,6,7,8,9,10,...,92,93,94,95,96,97,98,99,100,101
0,,,,,,,,,,,,,,,,,,,,,
Rk,1,2,3,4,5,6,7,8,9,10,...,Rk,81,82,83,84,85,86,87,88,89
Player,Craig Anderson,Alex Auld,Niklas Backstrom,Martin Biron,Ben Bishop,Brian Boucher,Martin Brodeur*,Ilya Bryzgalov,Peter Budaj,Scott Clemmensen,...,Player,Tim Thomas,Josh Tordjman,Vesa Toskala,Marty Turco,Steve Valiquette,Semyon Varlamov,Tomas Vokoun,Cam Ward,Kevin Weekes
Age,27,28,30,31,22,32,36,28,26,31,...,Age,34,24,31,33,31,20,32,24,33
Tm,FLA,OTT,MIN,PHI,STL,SJS,NJD,PHX,COL,NJD,...,Tm,BOS,PHX,TOR,DAL,NYR,WSH,FLA,CAR,NJD
GP,31,43,71,55,6,22,31,65,56,40,...,GP,54,2,53,74,15,6,59,68,16
GS,27,38,71,53,3,20,30,62,55,39,...,GS,53,2,52,74,12,5,55,68,13
W,15,16,37,29,1,12,19,26,20,25,...,W,36,0,22,33,5,4,26,39,7
L,7,18,24,19,1,6,9,31,29,13,...,L,11,2,17,31,5,0,23,23,5
T/O,5,7,8,5,1,3,3,6,5,1,...,T/O,7,0,11,10,2,1,6,5,0
GA,74,101,159,146,12,47,73,187,154,94,...,GA,114,8,166,203,39,13,138,160,32
SA,977,1141,2059,1718,112,563,870,1994,1531,1138,...,SA,1694,62,1518,1993,421,159,1855,1901,399
SV,903,1040,1900,1572,100,516,797,1807,1377,1044,...,SV,1580,54,1352,1790,382,146,1717,1741,367
SV%,0.924,0.911,0.923,0.915,0.893,0.917,0.916,0.906,0.899,0.917,...,SV%,0.933,0.871,0.891,0.898,0.907,0.918,0.926,0.916,0.92
GAA,2.71,2.47,2.33,2.76,2.94,2.18,2.42,2.98,2.86,2.39,...,GAA,2.1,4.08,3.26,2.81,2.84,2.37,2.49,2.44,2.42
SO,3,1,8,2,0,2,5,3,2,2,...,SO,5,0,1,3,1,0,6,6,0
GPS,7.6,7.2,15.6,11.5,0.5,3.9,5.9,11.4,7.6,7.9,...,GPS,14.7,0.1,6,9.6,2.5,1.1,14.6,12.9,2.9
MIN,1636,2449,4088,3177,245,1291,1814,3760,3232,2356,...,MIN,3259,118,3056,4327,823,329,3324,3928,795
QS,16,22,47,29,1,10,20,33,27,22,...,QS,39,0,23,38,7,4,33,43,8
QS%,0.593,0.579,0.662,0.547,0.333,0.5,0.667,0.532,0.491,0.564,...,QS%,0.736,0,0.442,0.514,0.583,0.8,0.6,0.632,0.615
RBS,6,4,9,7,0,1,5,13,14,5,...,RBS,3,0,13,22,1,1,4,10,1
GA%-,83,97,84,93,NaN,91,92,102,110,90,...,GA%-,74,NaN,120,111,101,NaN,81,92,88
GSAA,15.4,3.41,29.42,11.21,NaN,4.52,6.61,-4.53,-13.9,10.14,...,GSAA,41.02,NaN,-27.09,-20.62,-0.47,NaN,31.75,13.96,4.51
G,0,0,0,0,0,0,0,0,0,0,...,G,0,0,0,0,0,0,0,0,0
A,1,0,0,4,0,0,0,2,1,0,...,A,1,0,0,5,1,0,1,1,0
PTS,1,0,0,4,0,0,0,2,1,0,...,PTS,1,0,0,5,1,0,1,1,0
PIM,2,2,6,0,0,2,4,4,0,2,...,PIM,6,0,2,18,2,2,2,4,0

In [29]:
g0809= g0809t_new.T
g0809

,Rk,Player,Age,Tm,GP,GS,W,L,T/O,GA,...,MIN,QS,QS%,RBS,GA%-,GSAA,G,A,PTS,PIM
1,1,Craig Anderson,27,FLA,31,27,15,7,5,74,...,1636,16,0.593,6,83,15.4,0,1,1,2
2,2,Alex Auld,28,OTT,43,38,16,18,7,101,...,2449,22,0.579,4,97,3.41,0,0,0,2
3,3,Niklas Backstrom,30,MIN,71,71,37,24,8,159,...,4088,47,0.662,9,84,29.42,0,0,0,6
4,4,Martin Biron,31,PHI,55,53,29,19,5,146,...,3177,29,0.547,7,93,11.21,0,4,4,0
5,5,Ben Bishop,22,STL,6,3,1,1,1,12,...,245,1,0.333,0,NaN,NaN,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,85,Steve Valiquette,31,NYR,15,12,5,5,2,39,...,823,7,0.583,1,101,-0.47,0,1,1,2
98,86,Semyon Varlamov,20,WSH,6,5,4,0,1,13,...,329,4,0.8,1,NaN,NaN,0,0,0,2
99,87,Tomas Vokoun,32,FLA,59,55,26,23,6,138,...,3324,33,0.6,4,81,31.75,0,1,1,2
100,88,Cam Ward,24,CAR,68,68,39,23,5,160,...,3928,43,0.632,10,92,13.96,0,1,1,4
101,89,Kevin Weekes,33,NJD,16,13,7,5,0,32,...,795,8,0.615,1,88,4.51,0,0,0,0

In [30]:
g0809=g0809.set_index('Player')
g0809

,Rk,Age,Tm,GP,GS,W,L,T/O,GA,SA,...,MIN,QS,QS%,RBS,GA%-,GSAA,G,A,PTS,PIM
Player,,,,,,,,,,,,,,,,,,,,,
Craig Anderson,1,27,FLA,31,27,15,7,5,74,977,...,1636,16,0.593,6,83,15.4,0,1,1,2
Alex Auld,2,28,OTT,43,38,16,18,7,101,1141,...,2449,22,0.579,4,97,3.41,0,0,0,2
Niklas Backstrom,3,30,MIN,71,71,37,24,8,159,2059,...,4088,47,0.662,9,84,29.42,0,0,0,6
Martin Biron,4,31,PHI,55,53,29,19,5,146,1718,...,3177,29,0.547,7,93,11.21,0,4,4,0
Ben Bishop,5,22,STL,6,3,1,1,1,12,112,...,245,1,0.333,0,NaN,NaN,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Steve Valiquette,85,31,NYR,15,12,5,5,2,39,421,...,823,7,0.583,1,101,-0.47,0,1,1,2
Semyon Varlamov,86,20,WSH,6,5,4,0,1,13,159,...,329,4,0.8,1,NaN,NaN,0,0,0,2
Tomas Vokoun,87,32,FLA,59,55,26,23,6,138,1855,...,3324,33,0.6,4,81,31.75,0,1,1,2
Cam Ward,88,24,CAR,68,68,39,23,5,160,1901,...,3928,43,0.632,10,92,13.96,0,1,1,4
Kevin Weekes,89,33,NJD,16,13,7,5,0,32,399,...,795,8,0.615,1,88,4.51,0,0,0,0

In [31]:
g0809=g0809.drop(columns='Rk')
g0809

,Age,Tm,GP,GS,W,L,T/O,GA,SA,SV,...,MIN,QS,QS%,RBS,GA%-,GSAA,G,A,PTS,PIM
Player,,,,,,,,,,,,,,,,,,,,,
Craig Anderson,27,FLA,31,27,15,7,5,74,977,903,...,1636,16,0.593,6,83,15.4,0,1,1,2
Alex Auld,28,OTT,43,38,16,18,7,101,1141,1040,...,2449,22,0.579,4,97,3.41,0,0,0,2
Niklas Backstrom,30,MIN,71,71,37,24,8,159,2059,1900,...,4088,47,0.662,9,84,29.42,0,0,0,6
Martin Biron,31,PHI,55,53,29,19,5,146,1718,1572,...,3177,29,0.547,7,93,11.21,0,4,4,0
Ben Bishop,22,STL,6,3,1,1,1,12,112,100,...,245,1,0.333,0,NaN,NaN,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Steve Valiquette,31,NYR,15,12,5,5,2,39,421,382,...,823,7,0.583,1,101,-0.47,0,1,1,2
Semyon Varlamov,20,WSH,6,5,4,0,1,13,159,146,...,329,4,0.8,1,NaN,NaN,0,0,0,2
Tomas Vokoun,32,FLA,59,55,26,23,6,138,1855,1717,...,3324,33,0.6,4,81,31.75,0,1,1,2
Cam Ward,24,CAR,68,68,39,23,5,160,1901,1741,...,3928,43,0.632,10,92,13.96,0,1,1,4
Kevin Weekes,33,NJD,16,13,7,5,0,32,399,367,...,795,8,0.615,1,88,4.51,0,0,0,0

In [32]:
g0809.columns

Index(['Age', 'Tm', 'GP', 'GS', 'W', 'L', 'T/O', 'GA', 'SA', 'SV', 'SV%',
       'GAA', 'SO', 'GPS', 'MIN', 'QS', 'QS%', 'RBS', 'GA%-', 'GSAA', 'G', 'A',
       'PTS', 'PIM'],
      dtype='object', name=0)

In [33]:
g0809=g0809.rename(columns={'SO':'SUT'})
# 'SUT' will mean 'shutouts' , 'SOT' will be prefix for 'shootout'

In [34]:
g_shootout_0809=pd.DataFrame()
g_shootout_0809= pd.read_excel('./Stats/2008-09/2008-09goalies_shootout.xlsx', engine= 'openpyxl')
g_shootout_0809

              Player Team Att. Made Miss  Pct.
0   Jeff Deslauriers  EDM    3    0    3   100
1      Johan Hedberg  ATL   13    1   12  92.3
2   Mikael Tellqvist  PHX    8    1    7  87.5
3    Andrew Raycroft  COL    8    1    7  87.5
4       Jonas Hiller  ANA   31    5   26  83.9
..               ...  ...  ...  ...  ...   ...
62   Pascal Leclaire  CBJ    3    2    1  33.3
63   Jason LaBarbera  LAK   16   11    5  31.3
64    Cory Schneider  VAN    3    3    0     0
65       Matt Climie  DAL    2    2    0     0
66      Justin Pogge  TOR    2    2    0     0

[67 rows x 6 columns]

In [35]:
g_shootout_0809= g_shootout_0809.set_index('Player')

In [36]:
g_shootout_0809

                 Team Att. Made Miss  Pct.
Player
Jeff Deslauriers  EDM    3    0    3   100
Johan Hedberg     ATL   13    1   12  92.3
Mikael Tellqvist  PHX    8    1    7  87.5
Andrew Raycroft   COL    8    1    7  87.5
Jonas Hiller      ANA   31    5   26  83.9
...               ...  ...  ...  ...   ...
Pascal Leclaire   CBJ    3    2    1  33.3
Jason LaBarbera   LAK   16   11    5  31.3
Cory Schneider    VAN    3    3    0     0
Matt Climie       DAL    2    2    0     0
Justin Pogge      TOR    2    2    0     0

[67 rows x 5 columns]

In [37]:
g_shootout_0809= g_shootout_0809.rename(columns={'Att.':'SOT_Att','Scored':'SOT_Scored','Saved':'SOT_Saved','Pct.':'SOT_Pct'})
#originally changed made to scored, and miss to saved, and dropped team

In [38]:
g_shootout_0809

                 Team SOT_Att Made Miss SOT_Pct
Player
Jeff Deslauriers  EDM       3    0    3     100
Johan Hedberg     ATL      13    1   12    92.3
Mikael Tellqvist  PHX       8    1    7    87.5
Andrew Raycroft   COL       8    1    7    87.5
Jonas Hiller      ANA      31    5   26    83.9
...               ...     ...  ...  ...     ...
Pascal Leclaire   CBJ       3    2    1    33.3
Jason LaBarbera   LAK      16   11    5    31.3
Cory Schneider    VAN       3    3    0       0
Matt Climie       DAL       2    2    0       0
Justin Pogge      TOR       2    2    0       0

[67 rows x 5 columns]

In [134]:
goalies_0809= pd.merge(g0809,g_shootout_0809,how='inner', on='Player')

In [154]:
goalies_0809

,Age,Tm,GP,GS,W,L,T/O,GA,SA,SV,...,G,A,PTS,PIM,Team,SOT_Att,Made,Miss,SOT_Pct,Season
Player,,,,,,,,,,,,,,,,,,,,,
Craig Anderson,27,FLA,31,27,15,7,5,74,977,903,...,0,1,1,2,FLA,11,7,4,36.4,2008
Alex Auld,28,OTT,43,38,16,18,7,101,1141,1040,...,0,0,0,2,OTT,25,9,16,64,2008
Niklas Backstrom,30,MIN,71,71,37,24,8,159,2059,1900,...,0,0,0,6,MIN,21,5,16,76.2,2008
Martin Biron,31,PHI,55,53,29,19,5,146,1718,1572,...,0,4,4,0,PHI,17,5,12,70.6,2008
Ben Bishop,22,STL,6,3,1,1,1,12,112,100,...,0,0,0,0,STL,4,2,2,50,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marty Turco,33,DAL,74,74,33,31,10,203,1993,1790,...,0,5,5,18,DAL,43,16,27,62.8,2008
Steve Valiquette,31,NYR,15,12,5,5,2,39,421,382,...,0,1,1,2,NYR,12,3,9,75,2008
Tomas Vokoun,32,FLA,59,55,26,23,6,138,1855,1717,...,0,1,1,2,FLA,19,6,13,68.4,2008
Cam Ward,24,CAR,68,68,39,23,5,160,1901,1741,...,0,1,1,4,CAR,19,7,12,63.2,2008
Kevin Weekes,33,NJD,16,13,7,5,0,32,399,367,...,0,0,0,0,NJD,6,2,4,66.7,2008

In [155]:
g_copy= goalies_0809

In [156]:
g_copy['Season']= 2008

In [158]:
g_copy.head()

,Age,Tm,GP,GS,W,L,T/O,GA,SA,SV,...,G,A,PTS,PIM,Team,SOT_Att,Made,Miss,SOT_Pct,Season
Player,,,,,,,,,,,,,,,,,,,,,
Craig Anderson,27,FLA,31,27,15,7,5,74,977,903,...,0,1,1,2,FLA,11,7,4,36.4,2008
Alex Auld,28,OTT,43,38,16,18,7,101,1141,1040,...,0,0,0,2,OTT,25,9,16,64,2008
Niklas Backstrom,30,MIN,71,71,37,24,8,159,2059,1900,...,0,0,0,6,MIN,21,5,16,76.2,2008
Martin Biron,31,PHI,55,53,29,19,5,146,1718,1572,...,0,4,4,0,PHI,17,5,12,70.6,2008
Ben Bishop,22,STL,6,3,1,1,1,12,112,100,...,0,0,0,0,STL,4,2,2,50,2008

In [159]:
g2.head()

,Age,Tm,GP,GS,W,L,T/O,GA,SA,SV,...,G,A,PTS,PIM,Team,SOT_Att,Made,Miss,SOT_Pct,Season
Player,,,,,,,,,,,,,,,,,,,,,
Craig Anderson,27,FLA,31,27,15,7,5,74,977,903,...,0,1,1,2,FLA,11,7,4,36.4,2008
Alex Auld,28,OTT,43,38,16,18,7,101,1141,1040,...,0,0,0,2,OTT,25,9,16,64,2008
Niklas Backstrom,30,MIN,71,71,37,24,8,159,2059,1900,...,0,0,0,6,MIN,21,5,16,76.2,2008
Martin Biron,31,PHI,55,53,29,19,5,146,1718,1572,...,0,4,4,0,PHI,17,5,12,70.6,2008
Ben Bishop,22,STL,6,3,1,1,1,12,112,100,...,0,0,0,0,STL,4,2,2,50,2008

In [160]:
g_copy= g_copy.reset_index()

In [162]:
g_copy.head()

,Player,Age,Tm,GP,GS,W,L,T/O,GA,SA,...,G,A,PTS,PIM,Team,SOT_Att,Made,Miss,SOT_Pct,Season
0,Craig Anderson,27,FLA,31,27,15,7,5,74,977,...,0,1,1,2,FLA,11,7,4,36.4,2008
1,Alex Auld,28,OTT,43,38,16,18,7,101,1141,...,0,0,0,2,OTT,25,9,16,64,2008
2,Niklas Backstrom,30,MIN,71,71,37,24,8,159,2059,...,0,0,0,6,MIN,21,5,16,76.2,2008
3,Martin Biron,31,PHI,55,53,29,19,5,146,1718,...,0,4,4,0,PHI,17,5,12,70.6,2008
4,Ben Bishop,22,STL,6,3,1,1,1,12,112,...,0,0,0,0,STL,4,2,2,50,2008

In [163]:
g_copy=g_copy.set_index(['Season','Player'], inplace=False, append=True, drop=False)

In [164]:
g_copy

,,,Player,Age,Tm,GP,GS,W,L,T/O,GA,SA,...,G,A,PTS,PIM,Team,SOT_Att,Made,Miss,SOT_Pct,Season
,Season,Player,,,,,,,,,,,,,,,,,,,,,
0,2008,Craig Anderson,Craig Anderson,27,FLA,31,27,15,7,5,74,977,...,0,1,1,2,FLA,11,7,4,36.4,2008
1,2008,Alex Auld,Alex Auld,28,OTT,43,38,16,18,7,101,1141,...,0,0,0,2,OTT,25,9,16,64,2008
2,2008,Niklas Backstrom,Niklas Backstrom,30,MIN,71,71,37,24,8,159,2059,...,0,0,0,6,MIN,21,5,16,76.2,2008
3,2008,Martin Biron,Martin Biron,31,PHI,55,53,29,19,5,146,1718,...,0,4,4,0,PHI,17,5,12,70.6,2008
4,2008,Ben Bishop,Ben Bishop,22,STL,6,3,1,1,1,12,112,...,0,0,0,0,STL,4,2,2,50,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,2008,Marty Turco,Marty Turco,33,DAL,74,74,33,31,10,203,1993,...,0,5,5,18,DAL,43,16,27,62.8,2008
74,2008,Steve Valiquette,Steve Valiquette,31,NYR,15,12,5,5,2,39,421,...,0,1,1,2,NYR,12,3,9,75,2008
75,2008,Tomas Vokoun,Tomas Vokoun,32,FLA,59,55,26,23,6,138,1855,...,0,1,1,2,FLA,19,6,13,68.4,2008
76,2008,Cam Ward,Cam Ward,24,CAR,68,68,39,23,5,160,1901,...,0,1,1,4,CAR,19,7,12,63.2,2008
77,2008,Kevin Weekes,Kevin Weekes,33,NJD,16,13,7,5,0,32,399,...,0,0,0,0,NJD,6,2,4,66.7,2008

In [231]:
g2=g_copy

In [234]:
g2

,,,Player,Age,Tm,GP,GS,W,L,T/O,GA,SA,...,G,A,PTS,PIM,Team,SOT_Att,Made,Miss,SOT_Pct,Season
,Season,Player,,,,,,,,,,,,,,,,,,,,,
0,2008,Craig Anderson,Craig Anderson,27,FLA,31,27,15,7,5,74,977,...,0,1,1,2,FLA,11,7,4,36.4,2008
1,2008,Alex Auld,Alex Auld,28,OTT,43,38,16,18,7,101,1141,...,0,0,0,2,OTT,25,9,16,64,2008
2,2008,Niklas Backstrom,Niklas Backstrom,30,MIN,71,71,37,24,8,159,2059,...,0,0,0,6,MIN,21,5,16,76.2,2008
3,2008,Martin Biron,Martin Biron,31,PHI,55,53,29,19,5,146,1718,...,0,4,4,0,PHI,17,5,12,70.6,2008
4,2008,Ben Bishop,Ben Bishop,22,STL,6,3,1,1,1,12,112,...,0,0,0,0,STL,4,2,2,50,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,2008,Marty Turco,Marty Turco,33,DAL,74,74,33,31,10,203,1993,...,0,5,5,18,DAL,43,16,27,62.8,2008
74,2008,Steve Valiquette,Steve Valiquette,31,NYR,15,12,5,5,2,39,421,...,0,1,1,2,NYR,12,3,9,75,2008
75,2008,Tomas Vokoun,Tomas Vokoun,32,FLA,59,55,26,23,6,138,1855,...,0,1,1,2,FLA,19,6,13,68.4,2008
76,2008,Cam Ward,Cam Ward,24,CAR,68,68,39,23,5,160,1901,...,0,1,1,4,CAR,19,7,12,63.2,2008
77,2008,Kevin Weekes,Kevin Weekes,33,NJD,16,13,7,5,0,32,399,...,0,0,0,0,NJD,6,2,4,66.7,2008

In [ ]:
# ********should i keep point statistics for goalies???  --> is it indicative of how well a goalie
#*********plays a puck??? worth noting and investigating down the road ********

Need to make a for-loop that will consolidate all the edits i make to each season stats dataset,
that way i will have a bunch of clean datasets that i can just then start adding together